### ISSUE TITLE
Alfresco 7.1 Postgres can't access logs

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-docker-installer#103]
I did a vanilla setup of 7.1 using this generator. I accepted all defaults except the last I did ask for the setup.sh script to be added.

Alfresco would not start. Issue was that Postgres would not start. This was caused because ./logs/postgres is owned by my user and not 999. I chowned this logs folder and everything is now working.

**Comment by aborroy** [comment]
That issue is described in https://github.com/Alfresco/alfresco-docker-installer#docker-volumes

Should we add those permissions changes in the generator code?

**Comment by iohann95** [comment]
Angel, I don't know if i'm in the position to say it, but that seems to confuse a lot of new people trying to deploy Alfresco. I think would be really good if it was done automatically.

**Comment by aborroy** [comment]
I was studying this option for a while, but the `chown` command would require `sudo` privileges in many use cases. So I guess we can't help with something automatic at this point. 

We could create a helper shell script to be executed with `sudo` similar to:

```
mkdir ./data
mkdir ./data/solr-data
chown 33007 ./data/solr-data

mkdir ./data/postgres-data
chown 999 ./data/postgres-data

mkdir ./logs
mkdir logs/postgres-logs
chown 999 logs/postgres-logs
```

Should that be enough?

**Comment by douglascrp** [comment]
> I was studying this option for a while, but the `chown` command would require `sudo` privileges in many use cases. So I guess we can't help with something automatic at this point.
> 
> We could create a helper shell script to be executed with `sudo` similar to:
> 
> ```
> mkdir ./data
> mkdir ./data/solr-data
> chown 33007 ./data/solr-data
> 
> mkdir ./data/postgres-data
> chown 999 ./data/postgres-data
> 
> mkdir ./logs
> mkdir logs/postgres-logs
> chown 999 logs/postgres-logs
> ```
> 
> Should that be enough?

Hello

Yes, I think that should be enough.
There is just a typo on the postgresql logs parts, and the right commands would be:

#!/usr/bin/env bash

mkdir ./data
mkdir ./data/solr-data
chown 33007 ./data/solr-data

mkdir ./data/postgres-data
chown 999 ./data/postgres-data

mkdir ./logs
mkdir logs/postgres
chown 999 logs/postgres

**Comment by iohann95** [comment]
That looks cool!
