### ISSUE TITLE
Se puede seguir usando el postgres 13.1 en vez del postgres 13.3?

### ISSUE THREAD

**Issue by antoniorv75** [Alfresco/alfresco-docker-installer#107]
Hola,
En la página de github de alfresco community, la versión que ahora está como la 7.2 indica que el postgres que usa es el 13.3.
Yo tengo una version instalada de alfresco con contenedores, en concreto tengo la 7.0.1 con la version 13.1 de postgres y está apuntando a una base de datos física, no al contenedor de postgres que por defecto se configura en la instalación. Me preguntaba si en el upgrade a la 7.2 puedo conservar la version de postgres 13.1 o no. 
Muchas gracias
Un saludo y enhorabuena por el trabajo

**Comment by aborroy** [comment]
La versión de base de datos indicada es la versión con la que se prueban las _releases_. Por tanto, es la versión en la que se han ejecutado todas las pruebas y validaciones. Cuando se actualiza a una versión superior de Alfresco, puede seguir utilizándose la versión existente de base de datos, pero hay que tener en cuenta que la versión no ha sido probado.

En este caso, creo que resulta seguro seguir utilizando la 13.1, ya que en la 13.3 solo se incluyen parches de seguridad.

**Comment by antoniorv75** [comment]
Gracias Angel
un saludo
