### ISSUE TITLE
OCRmyPDF location change

### ISSUE THREAD

**Issue by aborroy** [Alfresco/alfresco-docker-installer#11]
From @phaleth:  
I've tested the installer you made here https://github.com/Alfresco/alfresco-docker-installer and found one problem, the image jbarlow83/ocrmypdf:latest uses different command to run ocrmypdf now, the last line in the file 'ocrmypdf/assets/ocr.sh' should be '/appenv/bin/ocrmypdf $@'

**Comment by phaleth** [comment]
The location of `ocrmypdf` binary has changed once again, this time it's `/usr/local/bin/ocrmypdf`.

https://github.com/jbarlow83/OCRmyPDF/commit/c3719d3b721bdcd7300c79192d6d18e23173f0b5#diff-ed3ef792c56bca0b45e534f8b1444c01

**Comment by aborroy** [comment]
Thanks, 0.1.0 includes the new path.
