### ISSUE TITLE
Accediendo a Alfresco API Explorer desde https://<nombre-maquina>/alfresco da error

### ISSUE THREAD

**Issue by antoniorv75** [Alfresco/alfresco-docker-installer#110]
Buenos días Angel,
Haciendo una instalación con proxy en https, configurado todo por 443 y con http con SOLR, he observado que desde el menú de alfresco https://ubuntu-maqueta/alfresco , cuando hacemos click en Alfresco API Explorer , da un error ya que no monta la direccion https://ubuntu-maqueta/api-explorer/ sino : http://ubuntu-maqueta:443/api-explorer/ mostrando un error de : 400 Bad Request
The plain HTTP request was sent to HTTPS port 

Si la url la cambias por la de https en la barra de direcciones entonces funciona la página de las APIs, pero en el proxy yo no he visto la opción correcta para hacer esto y en el fichero de configuración del yaml tampoco. Adjunto los ficheros de la instalación por defecto que he hecho con https para que lo veas por si me puedes ayudar, no cambié nada, lo dejé por defecto
La instalación que hice es la siguiente.:
GRACIAS DE ANTEMANO.

localadmin@ubuntu-maqueta:~/alfresco-aborroy/docker-compose-new$ yo alfresco-docker-installer

             ,****.
        ,.**. `*****  <-_
       ******** ***** ####
      $********::**** ####;
      _.-._`***::*** ######
    ,*******, *::* .;##### @
    **********,' -=#####',@@@
    ***' .,---, ,.-==@@@@@@@@
     * /@@@@@',@ @\ '@@@@@@@
      '@@@@/ @@@ @@@\ ':#'
      !@@@@ @@@@ @@@@@@@@@^
       @@@@ @@@@@ @@@@@@@'
        `"$ '@@@@@. '##'
             '@@@@;'

     DOCKER COMPOSE ALFRESCO

? Which ACS version do you want to use? 7.1
? How may GB RAM are available for Alfresco (16 is minimum required)? 16
? Do you want to use HTTPs for Web Proxy? Yes
? What is the name of your server? ubuntu-maqueta
? Choose the password for your admin user admin
? What HTTPs port do you want to use (all the services are using the same port)? 443
? Do you want to use FTP (port 2121)? No
? Do you want to use MariaDB instead of PostgreSQL? No
? Are you using different languages (this is the most common scenario)? Yes
? Would you like to use HTTP, HTTPs or Shared Secret for Alfresco-SOLR communication? http
? Do you want to use credentials for Events service (ActiveMQ)? No
? Do you want to create an internal SMTP server? No
? Do you want to create an internal LDAP server? No
? Select the addons to be installed:
? Are you using a Windows host to run Docker? No
? Do you want to use a start script? No

[nginx.conf.txt](https://github.com/Alfresco/alfresco-docker-installer/files/8038785/nginx.conf.txt)
[docker-compose.yml.txt](https://github.com/Alfresco/alfresco-docker-installer/files/8038786/docker-compose.yml.txt)

**Comment by aborroy** [comment]
Gracias por reportar el problema.

He subido el parche en la última versión (0.4.7)

**Comment by antoniorv75** [comment]
Muchas gracias Angel!, Qué rapidez.
un saludo
