### ISSUE TITLE
Alfresco-global.properties External Volume Mapping

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/alfresco-docker-installer#117]
Hi,

I did an installation using the Angel project through Yeoman and as it is not updated to version 7.1, so I changed the values ​​of the .env file as follows:
# Docker Image versions
ALFRESCO_CE_TAG=7.1.1.2
SEARCH_CE_TAG=2.0.2
SHARE_TAG=7.1.1.2
ACA_TAG=2.8.0
POSTGRES_TAG=13.3
TRANSFORM_ENGINE_TAG=2.5.6
ACTIVEMQ_TAG=5.16.1

Also in Alfresco's Dockerfile manually include a copy of api-explorer-7.1.0.war into the webapps folder of the Alfresco container using:
# Install api-explorer webapp for REST API
COPY api-explorer-7.1.0.war $TOMCAT_DIR/webapps/api-explorer.war

But when trying to map the contents of the shared/classes folder of the Alfresco container to an external volume, it generates a keystroke error (informing that folders after this one are empty).

Procedures to map container content on external volume:
- I create a folder called global below the "data" folder of the project structure.
- run chown -R 33000 data/global
- in docker-compose.yml when creating the Alfresco repository container I generate a volume mapped like this: 
           - ./data/global:/usr/local/tomcat/shared/classes

And this way it generates the error. Can anyone help me with this?

Or is there any update of the Angel project to version 7.1?

Thanks

**Comment by aborroy** [comment]
Why don't use this project?
It includes support for 7.1

**Comment by marcogianini** [comment]
Hi Angel.

I tried more when running generator-alfresco-docker-installer without root and then running yo alfresco-docker-installer it doesn't download the project.

Version:
Node - 12.20.1
Npm - 6.14.10
Yo - 4.3.0

With root it does not run yo and generates the following error:
Cannot find module '/root/.npm-packages/lib/node_modules/yo/node_modules/spawn-sync/postinstall'

How could you help me?

**Comment by marcogianini** [comment]
Thanks.

Marco Gianini
