### ISSUE TITLE
Password error

### ISSUE THREAD

**Issue by nextOver** [Alfresco/alfresco-docker-installer#118]
The default login password: admin:admin does not work. Is there another password?

**Comment by aborroy** [comment]
Any error message in the logs?

**Comment by Jonbj** [comment]
Did you do the steps of Docker Volume configuration?

https://github.com/Alfresco/alfresco-docker-installer#docker-volumes

**Comment by nextOver** [comment]
Yes I put permissions on the directories. Now I see errors in the container ocker-compose_solr6 .
`Config XML parse warning in "solrres:/solrconfig.xml", line 1959, column 88: Include operation failed, reverting to fallback. Resource error reading file as XML (href='solrconfig_insight.xml'). Reason: Can't find resource 'solrconfig_insight.xml' in classpath or '/opt/alfresco-search-services/solrhome/alfresco'` and others erros later.

**Comment by nextOver** [comment]
Solved, problem was my amount of ram memory. Thanks
