### ISSUE TITLE
localhost redirect from share

### ISSUE THREAD

**Issue by narkuss** [Alfresco/alfresco-docker-installer#13]
Hi all,
first of all, thanks for this amazing tool, it's very valuable to keep learning about Alfresco deployment, project structure and good practices with new versions. I will apply some ideas taken from this project for sure in our future deployments.
I don't know if it's an issue or not, but when I try to deploy this solution on a server other than localhost, I can't access to https://IP/share, it redirects me to https://localhost/share/page. I can neither login, because share detects a possible CSRF attack, coming from localhost.
They all seemed to came from the same place, somewhere replacing my server IP for localhost.
I'm creating a pull request with my solution, erasing the proxyName="localhost" from the tomcat connector in share, written by the Dockerfile. Hope this helps someone else.
Please, if that's not an issue, tell me why (security considerations, not developed for deployments other than localhost, etc etc).

Gracias Ángel, sigue ahí!

**Comment by aborroy** [comment]
This option has been fixed by https://github.com/Alfresco/alfresco-docker-installer/pull/15

Now you have the ability to add your server name if it's different from `localhost`
