### ISSUE TITLE
add option to install alfresco-share-online-edition-addon

### ISSUE THREAD

**Issue by frhack** [Alfresco/alfresco-docker-installer#136]
Add option to install the add on for on line libreOffice edit

https://github.com/zylklab/alfresco-share-online-edition-addon

**Comment by aborroy** [comment]
Is that add-on working with Alfresco 6.x / 7.x?

**Comment by frhack** [comment]
> Is that add-on working with Alfresco 6.x / 7.x?

Hi according to [this](https://github.com/zylklab/alfresco-share-online-edition-addon/issues/13) open issue, at this time is working with 5.1 6.1 but not in 7.x

Hope it will be fixed

**Comment by frhack** [comment]
> In that case, I suggest you to deploy the JAR file manually.
> 
> Just copy the JAR to your `share/modules/jar` folder and it works.

Update: the addon works correctly in 5.x 6.x 7.x

The problem in 7.x was due to this issue https://github.com/Alfresco/alfresco-docker-installer/issues/137

Please fix it anc consider to add the add option to install alfresco-share-online-edition-addon

thanks
