### ISSUE TITLE
wrong files ownership

### ISSUE THREAD

**Issue by frhack** [Alfresco/alfresco-docker-installer#137]
There are some  file permissions to fix.
Notably the active-mq ones is required in order to start the service

> yo alfresco-docker-installer --acsVersion=7.1 --ram=16 --crossLocale=true --volumesscript=true --https=true --serverName=alfresco.sanvc.local --port=443 --password=admin --ftp=false --mariadb=false --smtp=false  --ldap=false --addons="" --windows=false --startscript=false

sudo chown -R 33000 logs/alfresco/
sudo chown -R 33000 data/alf-repo-data
**sudo chown -R 33031 data/activemq-data/**

**Comment by aborroy** [comment]
Adding this information to README.md and fixing the [create_volumes.sh](https://github.com/Alfresco/alfresco-docker-installer/blob/master/generators/app/templates/scripts/create_volumes.sh) is enough?

**Comment by frhack** [comment]
> Adding this information to README.md and fixing the [create_volumes.sh](https://github.com/Alfresco/alfresco-docker-installer/blob/master/generators/app/templates/scripts/create_volumes.sh) is enough?

yes,  but why not add give the option to install the addon ?

**Comment by aborroy** [comment]
Sorry, what addon?

**Comment by frhack** [comment]
> Sorry, what addon?

the addon to edit online document with LibreOffice

https://github.com/Alfresco/alfresco-docker-installer/issues/136

**Comment by aborroy** [comment]
Is the addon working for ACS 6 & 7?

**Comment by frhack** [comment]
> Is the addon working for ACS 6 & 7?

yes if we resolve this "wrong file ownership" issue

**Comment by douglascrp** [comment]
I've just found another problem with the folder permissions, and I am creating a new PR fixing it.
