### ISSUE TITLE
OOTB Support Tool-Active Session

### ISSUE THREAD

**Issue by SanjayBandhniya** [Alfresco/alfresco-docker-installer#140]
I have create alfresco7.2 using alfresco docker-installer.
I am trying to access active session from alfresco console(http://localhost:8080/alfresco) and getting error popup.
Is this issue from my side or addon side?
<img width="338" alt="Screenshot_1" src="https://user-images.githubusercontent.com/10328297/172758821-642bd0d8-823f-4bd9-ada3-4c39f1cccbe1.png">

**Comment by aborroy** [comment]
That is related with a problem related to deploying the add-on with ACS 7.2

I've registered a new ticket on the project to get this tracked:
https://github.com/OrderOfTheBee/ootbee-support-tools/issues/192

**Comment by SanjayBandhniya** [comment]
Hi,
Could you provide update on resolution? Is this resolved?

**Comment by aborroy** [comment]
Not yet solved, still pending to be merged:
https://github.com/OrderOfTheBee/ootbee-support-tools/pull/190
