### ISSUE TITLE
Unable to authenticate using the correct credentials

### ISSUE THREAD

**Issue by khorjames** [Alfresco/alfresco-docker-installer#143]
The docker container is running but I am unable to log in using admin for username and admin for password. I googled but I can't find any solution to reset the password.

**Comment by aborroy** [comment]
Alfresco container didn’t started. Default credentials are admin/admin

**Comment by nelsonrc** [comment]
I running on windows host, i have de same problem,

**Comment by aborroy** [comment]
This may help: https://hub.alfresco.com/t5/alfresco-content-services-blog/alfresco-login-issues-amp-how-to-solve-them/ba-p/313602
