### ISSUE TITLE
Solr startup error with alf 7.2 and --solrHttpMode=secret

### ISSUE THREAD

**Issue by federicotarantino** [Alfresco/alfresco-docker-installer#144]
Hi,
there is an error with alfresco 7.2 and --solrHttpMode=secret

Step to reproduce:
$ yo alfresco-docker-installer --acsVersion=7.2 --ram=16 --mariadb=false --crossLocale=true --smtp=false --ldap=false --addons=js-console --startscript=false --volumesscript=true --https=false --serverName=localhost --password=admin --port=80 --ftp=false --solrHttpMode=secret --activeMqCredentials=false --windows=false

$ sudo ./create-volumes.sh
$ docker compose up

**Comment by aborroy** [comment]
It worked as expected on my side.

What is the error? Can you attach some details?

**Comment by federicotarantino** [comment]
I retried and it works. I had the error when i changed the solrHttpMode from "https" to "secret", and recreate containers. I think depends of "keystore" volume. You can close/delete issue, sorry for the spent time

**Comment by aborroy** [comment]
No worries, thanks for your feedback.
