### ISSUE TITLE
Log Solr6

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/alfresco-docker-installer#147]
Hello everybody.

We are having a hard time identifying and parsing Solr logs in the project version of Angel.

The Solr Web Console in the Logging option displays errors and warms content that I cannot find inside the solr.log file that is inside the Solr6 container. Is there any other way or documentation that tells me how I can monitor these logs?

It also generates this error attached as an image on the ticket.

Can you help us please.
![errores_solr](https://user-images.githubusercontent.com/40039143/195137549-c6b46dfa-b934-42d7-8759-ae617e59b7f8.jpeg)

**Comment by aborroy** [comment]
Are these errors available when inspecting solr6 container logs?

The error attached in this issue is related to some invalid JSON response generated by the repository. You can try performing the REST request to get the full response and to identify the problem.

**Comment by marcogianini** [comment]
I'm testing with the environment and I will return with the result.
