### ISSUE TITLE
Access Web Console Solr - Alfresco 7.2

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/alfresco-docker-installer#148]
Good Morning.

I have the default project installation and installed with https and Solr using https communication as well.

I kept everything default to be able to test and I can't in any way open the Solr console in the browser.

I also did a test using secret communication, but I can't open the Solr console either.

It's giving me an error "Failed to execute script 'classpath* :alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/doclist.get.js': 09196367 Failed to execute search: +ID:"" +( TYPE:"content" OR TYPE:"app :filelink" OR TYPE:"folder")" and all I found is Solr and I would like to see the Solr Console to see logs, workspace, etc.

Can you tell me what is the difference between the two ways the browser communicates with the Solr Console?

**Comment by aborroy** [comment]
What URL are you trying to access?
That error is coming from the repository, not from the SOLR side

**Comment by aborroy** [comment]
Ok, so that error has nothing to see with it.

You need to use the "browser.p12" certificate for SSL (produced by the alfresco-ssl-generator) for mTLS and a browser add-on (like ModHeader) to add the secret header `X-Alfresco-Search-Secret:secret` when using secret mode.

**Comment by marcogianini** [comment]
Thanks
