### ISSUE TITLE
Tomcat insufficient cache size

### ISSUE THREAD

**Issue by Thyfas** [Alfresco/alfresco-docker-installer#150]
That message is being showed on catalina log of Alfresco Share. /logs/share/catalina.log
And i cant use the addons, to sign or edit documents in Share maybe related because the components is loading forever? I tried allocate a fixed size on context.xml of containerd config file of tomcat that i have found a some foruns i find a similar situation but it doesn't work

![tomcat](https://user-images.githubusercontent.com/107195530/201190190-1f0b5a87-0b82-4756-b130-ca305403d574.png)

**Comment by aborroy** [comment]
Did you try this approach?

https://hub.alfresco.com/t5/alfresco-content-services-forum/insufficient-free-space-available-after-evicting-expired-cache/m-p/307547#M24494

**Comment by iohann95** [comment]
Add this line on the share Dockerfile:

`RUN sed -i '/<Context>/a <Resources cacheMaxSize="51200" />' /usr/local/tomcat/conf/context.xml`

That's what I did. I actually was going to open a ticket and suggest that this could be added to the project.

**Comment by Thyfas** [comment]
Hello, I'm closing this issue for now, apparently the e-sing add-on needs an app to use, and it doesn't work in Chrome either.
