### ISSUE TITLE
Each delete document move to each user trash and ContentStore.deleted 

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/alfresco-docker-installer#151]
Hi,

I have installed your package again in a Linux 22.04 environment, following the questions of creating the installer package and its folders in its default form.

We began to observe that when deleting a document it does not record this information in contentstore.deleted or in the trash of the user who deleted it.

Is there any configuration I need to add for this to apply. Because I want that when deleting a document it goes to the user's trash and also remains in the contentstore.deleted folder.

I did a test using http and https, and both the scenario is the same.

Marco Gianini

**Comment by iohann95** [comment]
I think you're better of asking this one on the official Alfresco forums... Doesn't seem to be related to the installer.
