### ISSUE TITLE
an error occured while running alfresco-docker-installer:app#writing

### ISSUE THREAD

**Issue by guilhermepolicarpo** [Alfresco/alfresco-docker-installer#154]
![image](https://user-images.githubusercontent.com/13804537/215924444-b214dfea-9b0a-40df-9b88-4dd35b4fef35.png)

How can I solve this problem?

**Comment by guilhermepolicarpo** [comment]
I tried to run on ubuntu with wsl2 and docker installed on windows

**Comment by delacosta456** [comment]
hi
i am also having this issue on ubuntu server 20.4.

Can somebody help please

**Comment by aborroy** [comment]
Try using following ENV variable before running the app:

```
export NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by aborroy** [comment]
Additional workarounds available in: https://www.newline.co/@kchan/how-to-fix-the-error-errorerror0308010cdigital-envelope-routinesunsupported--0f8d3f17

Alfresco password is generated using MD4 algorithm, that provokes this error for NodeJS 17+

**Comment by delacosta456** [comment]
hi
The ENV variable option worked for me

thanks
