### ISSUE TITLE
ubuntu hidden folder regarding yo Alfrescko-docker-installer

### ISSUE THREAD

**Issue by delacosta456** [Alfresco/alfresco-docker-installer#155]
hi
i don't know if there is a reason for this behavior but it looks like  the installer if executed from a hidden folder (Ex: /home/{username}/**.myapp**/alfre/docker-compose) will not generate expected outputs (alfresco's files and folder, docker-compose file, scripts files and) inside this location from which this installer is executed. Instead the are saved to Home folder.

Is there anyway to avoid that ?

Thanks

**Comment by aborroy** [comment]
You can always copy generated files and folders to desired target once generated.
