### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by sergiobaiao** [Alfresco/alfresco-docker-installer#156]
Hi there,

Every single time i run i get this message at the end:

Error alfresco-docker-installer 

EACCES: permission denied, open '/files/alfresco/.env'
┌───────────────────────────────────────────────────┐
│              yo update check failed               │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘

Tried to run as root, with sudo, nothing changes. Also ran the chown, but didn't work. Can you help?

**Comment by aborroy** [comment]
Linked to https://github.com/aborroy/alfresco-installer/issues/2
