### ISSUE TITLE
Smart Folders Enabled

### ISSUE THREAD

**Issue by CPD-GrupoAnchieta** [Alfresco/alfresco-docker-installer#159]
According alfresco docs to use the Smart Folders, its necessary to configurate something on alfresco-global.properties

>https://docs.alfresco.com/content-services/latest/config/smart-folders/

>In the config file in <tomcat>/shared/classes/alfresco-global.properties

add these line:
```YAML
smart.folders.enabled=true
```

but i can't find it in anyone container or volume to configure. In ACS container the file exist but dont have lines on it.

**Comment by aborroy** [comment]
Add the setting to `alfresco` service configuration in **JAVA_OPTS** section as:

`
-Dsmart.folders.enabled=true
`

Modifying the alfresco-global.properties has been replaced by setting Java environment variables when using containers.
