### ISSUE TITLE
Logout redirects to http://mydomain.com:8080

### ISSUE THREAD

**Issue by apiening** [Alfresco/alfresco-docker-installer#16]
My relevant selection on the `alfresco-docker-installer` was:
Do you want to use HTTPs for Web Proxy? `No`
What is the name of your server? `mydomain.com`
What HTTP port do you want to use (all the services are using the same port)? `8080`

I'm using a reverse proxy in front of the nginx-proxy for HTTPS.
Therefore I added these lines to `share/Dockerfile`:
```
RUN sed -i '/Connector port="8080"/a scheme="https" secure="true"' /usr/local/tomcat/conf/server.xml && \
   sed -i '/Connector port="8080"/a proxyName="mydomain.com" proxyPort="443"' /usr/local/tomcat/conf/server.xml
```

I can log in to alfresco share at `https://mydomain.com/share/` and everything works fine.
However, when I click on <username>/logout I get redirected to `http://mydomain.com:8080` which times out.

I can't figure out the option / setting that is relevant so that Alfresco Share uses the correct logout URL which would be `https://mydomain.com`.

Any help or hint is greatly appreciated.

Andreas

**Comment by aborroy** [comment]
You can use `alfresco-docker-installer` to generate an HTTPs working configuration. And compare what's missing in your nginx-proxy configuration.

**Comment by apiening** [comment]
Thanks @aborroy,
that's a good recommendation. I will do this and compare the configs.
But my guess is, that it is not the nginx config that decides the redirect target of the logout link generated by `Alfresco share`. Am I wrong?
To clarify: I'm not using nginx as the front facing ssl proxy. Instead I've putted an external SSL proxy (`traefik` if that matters) in front of the bundled nginx proxy which is configured for HTTP:
```




                                                                                        +--------------+
                                                                              +-------> |Alfresco      |
                                                                              |         +--------------+
  +------------------------+         +--------------------------------------+ |
  |External frontend proxy |  +--->  |HTTP nginx proxy on port 8080         | |         +--------------+
  |for SSL encryption      |         |generated by alfresco-docker-installer| +-------> |Alfresco share|
  +------------------------+         +--------------------------------------+ |         +--------------+
                                                                              |
                                                                              |         +--------------+
                                                                              +-------> |...           |
                                                                                        +--------------+



```
This way I can route multiple domains to different things and use automatic letsencrypt certificate generation and renewal.

Thinking of it, `Alfresco share` may detect that it was called via port `8080` on plain `http` and generate the logout redirect target url based on that.
If so, is there a way to override this value with a parameter or setting?

**Comment by apiening** [comment]
I have generated a clean docker-compose environment in another folder with `alfresco-docker-installer` and at the question `Do you want to use HTTPs for Web Proxy?` I answered `Yes` and I accepted the default SSL port `443`.
But the issue I initially faced persists: When I try to logout from Alfresco share I get redirected to `http://mydomain.com:8080` which ends with a timeout.

This issue does not seem to be related with my frontend proxy config, since the behaviour is the same with the setup generated by the `alfresco-docker-installer`.

I have done a setup with exactly the same settings a few weeks ago and did not face the issue there. I'm still trying to compare the settings to figure out if there is some setting I missed that causes this issue, no luck until now.

It would be nice if someone can try a basic setup with the latest `alfresco-docker-installer` with https proxy to confirm if this issue is reproducable.

**Comment by aborroy** [comment]
I've created a fake localhost as:

```
$ cat /etc/hosts
127.0.0.1	localhost mydomain.com
255.255.255.255	broadcasthost
::1             localhost
```

After that, using version 0.0.8, I've created a Docker Compose template with following options:

```
? Which ACS version do you want to use (6.2 is EA only)? 6.1
? How may GB RAM are available for Alfresco (8 is minimum required)? 12
? Do you want to use HTTPs for Web Proxy? Yes
? What is the name of your server? mydomain.com
? What HTTPs port do you want to use (all the services are using the same port)? 443
? Do you want to use MariaDB instead of PostgreSQL? No
? Are you using different languages (this is the most common scenario)? Yes
? Do you want to create an internal SMTP server? No
? Do you want to create an internal LDAP server? No
? Select the addons to be installed: (Press <space> to select, <a> to toggle all, <i> to invert selection)JavaScri
pt Console 0.6, Order of the Bee Support Tools 1.0.0.0, Share Site Creators 0.0.7
   create .env
   create docker-compose.yml
   create alfresco/Dockerfile
   create alfresco/modules/amps/empty
   create alfresco/modules/jars/empty
   create share/Dockerfile
   create share/modules/amps/empty
   create share/modules/jars/empty
   create search/Dockerfile
   create config/nginx.conf
   create config/nginx.htpasswd
   create config/cert/localhost.cer
   create config/cert/localhost.key
   create alfresco/modules/amps/javascript-console-repo-0.6.0.amp
   create share/modules/amps/javascript-console-share-0.6.0.amp
   create alfresco/modules/amps/support-tools-repo-1.1.0.0-amp.amp
   create share/modules/amps/support-tools-share-1.1.0.0-amp.amp
   create alfresco/modules/amps/share-site-creators-repo-0.0.7.amp
   create share/modules/amps/share-site-creators-share-0.0.7.amp
```

When running Docker...

```
$ docker-compose up --build --force-recreate
```

https://mydomain.com/share works as expected.

**Comment by apiening** [comment]
Hi @aborroy,
thank you for your test, but this works for me as well!
Please can you log in to your https://mydomain.com/share (admin user with default credentials is fine) and click on the logout option in the username popup menue?
Are you redirected to the https://mydomain.com/share logon screen or are you getting a timeout since you're redirected to http://mydomain.com:808/share?

**Comment by aborroy** [comment]
It looks like logout works fine as well for me. No clues on what's happening on your side...

**Comment by aborroy** [comment]
Anyway, I've seen that there was an error in `docker-compose.yml` generation. 

Check release 0.0.9 to see if that helps with your problem.

**Comment by apiening** [comment]
Hi @aborroy,
I can confirm that it works with a local setup (/etc/hosts based) on a clean machine with the latest version of `alfresco-docker-installer`.
I will give it another shot on the production system with the latest version and / or compare the generated config and report.

**Comment by aborroy** [comment]
Thanks for your feedback @apiening 
Let us know if we can help in any way.
