### ISSUE TITLE
how to upgrade to new Alfresco version

### ISSUE THREAD

**Issue by frhack** [Alfresco/alfresco-docker-installer#160]
Hi, is there a way to upgrade an Alfresco installation created by alfresco-docker-installer to a new version ?

For example from alfresco 7.2 to Alfresco 7.3

Thanks

**Comment by aborroy** [comment]
There is no automatic tool to perform the upgrade.

I suggest you to create a 7.3 Docker Compose template and to compare it with your existing 7.2 deployment. This would help you to identify environment variables, addons and other configurations you need to apply to the new version.

**Comment by frhack** [comment]
> There is no automatic tool to perform the upgrade.
> 
> I suggest you to create a 7.3 Docker Compose template and to compare it with your existing 7.2 deployment. This would help you to identify environment variables, addons and other configurations you need to apply to the new version.


what if I  install  7.3 and restore the backup and configuration from 7.2 ?

**Comment by aborroy** [comment]
Yes, that should be the recommended approach.

You should be able to re-use external volumes for DB, FileSystem and SOLR indexes when upgrading to 7.3.

**Comment by sergiobaiao** [comment]
> Yes, that should be the recommended approach.
> 
> You should be able to re-use external volumes for DB, FileSystem and SOLR indexes when upgrading to 7.3.

Can you clarify on that? Is there a step-by-step guide on how to perform a full backup and restore so we can migrate do a newer version?

**Comment by aborroy** [comment]
This may help: https://hub.alfresco.com/t5/alfresco-content-services-blog/creating-and-restoring-backups-for-alfresco-with-docker-compose/ba-p/305070
