### ISSUE TITLE
about mimetypes.restricted.expression

### ISSUE THREAD

**Issue by Amazingzzl** [Alfresco/alfresco-docker-installer#162]
Can we use this plugin in 7.x version ？
https://github.com/keensoft/alfresco-mimetype-blocker

**Comment by aborroy** [comment]
It works with 7.x

If you want to build it from scratch, you need to modify this file https://github.com/keensoft/alfresco-mimetype-blocker/blob/master/mimetype-blocker-repo/pom.xml to avoid getting missing library "spring-social-facebook":

`    <dependencies>
        
        <dependency>
            <groupId>${alfresco.groupId}</groupId>
            <artifactId>alfresco-repository</artifactId>
            <exclusions>
            <exclusion>
              <groupId>org.springframework.social</groupId>
              <artifactId>spring-social-facebook</artifactId>
            </exclusion>
      </exclusions>
        </dependency>
    </dependencies>`
