### ISSUE TITLE
Error on generation.

### ISSUE THREAD

**Issue by mjordan79** [Alfresco/alfresco-docker-installer#164]
Hello, I've installed nodejs 18.16.0 LTS
Yeoman is version: 4.3.1

I execute the project by launching:
yo alfresco-docker-installer

I answer the questions (I'm on Windows, running docker desktop 4.19 (docker server v. 23.0.5)

The process go in error with the following error:
× An error occured while running alfresco-docker-installer:app#writing
Error alfresco-docker-installer

error:0308010C:digital envelope routines::unsupported

Nothing is being generated.

Any help? Thank you very much.,

**Comment by aborroy** [comment]
Depending on your terminal, run one of the commands below:

```
# macOS, Linux and Windows Git Bash
export NODE_OPTIONS=--openssl-legacy-provider

# Windows Command Prompt:
set NODE_OPTIONS=--openssl-legacy-provider

# Windows PowerShell:
$env:NODE_OPTIONS="--openssl-legacy-provider"
```

**Comment by aborroy** [comment]
Thanks @mjordan79 

Mention added in the README at https://github.com/Alfresco/alfresco-docker-installer/commit/5af9f6ecd4bd731124a5cbc2f03a0556891158fb
