### ISSUE TITLE
Install WCMQS Application

### ISSUE THREAD

**Issue by sergiobaiao** [Alfresco/alfresco-docker-installer#167]
Hi there,

I'm trying to install the WCMQS application ([https://mvnrepository.com/artifact/org.alfresco/alfresco-wcmqs-web](https://mvnrepository.com/artifact/org.alfresco/alfresco-wcmqs-web)) using the supplied instructions (copying the amps to the modules/amps directories) but had no success. 

I've cleared my docker images, ran docker system prune, rebuilt the whole thing, but WCMQS doesn't show up on Customize Dashboard page nor in the Modules page at Admin Tools.

The WCMQS package has two .war files alongside the amps, and i don't know what to do with them.
I got the WCMQS zip from this link: [https://artifacts.alfresco.com/nexus/content/repositories/public/org/alfresco/alfresco-wcmqs-distribution/23.1.0.126/alfresco-wcmqs-distribution-23.1.0.126.zip](https://artifacts.alfresco.com/nexus/content/repositories/public/org/alfresco/alfresco-wcmqs-distribution/23.1.0.126/alfresco-wcmqs-distribution-23.1.0.126.zip)

Can you please advice?

**Comment by aborroy** [comment]
Latest version supported for WCMQS is 5.2. It doesn't work with later versions.

**Comment by sergiobaiao** [comment]
Is there anything like it for 7.x versions?
