### ISSUE TITLE
Order of the Bee Support Tools 1.2.0.0 doesn't work with ACS 7.4

### ISSUE THREAD

**Issue by aborroy** [Alfresco/alfresco-docker-installer#173]
Since ACS 7.4 upgraded from Log4j to Log4j2, OOTB Support Tools 1.2 is not compatible with Share webapp. Share service is not starting when deploying the AMP on it.

It's required to remove this addon as an alternative for ACS 7.4

**Comment by DejmalDavid** [comment]
They wanna add it in version 1.2.1.0  https://github.com/OrderOfTheBee/ootbee-support-tools/issues/207

As substitute I use only Javacript console 0.7 https://github.com/share-extras/js-console, witch work with Alf 7.4
