### ISSUE TITLE
Can't find thumbnail-service-context.xml

### ISSUE THREAD

**Issue by jpbuttet** [Alfresco/alfresco-docker-installer#18]
Hello,

I'd like to increase the size of thumbnails generated on the share document list detailed view.
In order to do this, I would like to view the thumbnail-service-context.xml file but was not able to find it within the Alfresco container. Could you please tell me where this file is located ?

Thanks in advance.

**Comment by aborroy** [comment]
Thos file is included inside **alfresco-repository.jar**

In order to override a Spring Bean, add your XML file to Alfresco Extension folder:

/usr/local/tomcat/tomcat/shared/classes/alfresco/extension

**Comment by jpbuttet** [comment]
Thank you, best regards.
