### ISSUE TITLE
Error alfresco-docker-installer - Invalid argument expected string

### ISSUE THREAD

**Issue by SanjayBandhniya** [Alfresco/alfresco-docker-installer#183]
I am using alfresco-docker-installer for window and facing following error.

× An error occured while running alfresco-docker-installer:app#prompting
Error alfresco-docker-installer

Invalid argument expected string.
![Screenshot_1](https://github.com/Alfresco/alfresco-docker-installer/assets/10328297/df303be4-1103-40e6-9a0d-2970aee068a7)

**Comment by aborroy** [comment]
Thanks for your feedback @SanjayBandhniya 
Issue should be solved with this patch.

**Comment by SanjayBandhniya** [comment]
which patch?

**Comment by aborroy** [comment]
Just use the latest version (0.8.1)
