### ISSUE TITLE
Solr - Java memory parameters are ignored

### ISSUE THREAD

**Issue by luca86r** [Alfresco/alfresco-docker-installer#185]
Hi,
the options "-XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80" specified in the solr6 service under the environment variable "SOLR_OPTS", seem to be ignored.

Starting the container with mem_limit set to 4 GB, the heap size of solr is set to 1GB.

The Solr container uses OpenJDK v17 and I haven't found documentation for this specific JVM; however from Openj9 documentation (https://eclipse.dev/openj9/docs/xxinitialrampercentage/): "If you set a value for -Xms, the -XX:InitialRAMPercentage option is ignored. If you set a value for -Xmx, the -XX:MaxRAMPercentage option is ignored.".

Upon checking the solr.in.sh file, I noticed that the parameters "-Xms1g -Xmx1g" are set.

Possibile solutions:
* use -Xms and -Xmx parameters intead of -XX:MinRAMPercentage and -XX:MaxRAMPercentage
* change the content of the solr.in.sh file removing -Xms and -Xmx parameters

**Comment by aborroy** [comment]
Version 0.8.2 should fix this problem.

Waiting to your feedback before closing this issue.
