### ISSUE TITLE
Your credentials were not recognized or Alfresco

### ISSUE THREAD

**Issue by Ramdane34** [Alfresco/alfresco-docker-installer#188]
Good morning,
I can't connect with
login: admin and password: admin
I have this error:
Your credentials were not recognized or Alfresco Content Services may not be currently available.
do you know why?
Thank you so much

**Comment by aborroy** [comment]
https://hub.alfresco.com/t5/alfresco-content-services-blog/alfresco-login-issues-amp-how-to-solve-them/ba-p/313602
