### ISSUE TITLE
Customize Share themes CSS

### ISSUE THREAD

**Issue by quecot** [Alfresco/alfresco-docker-installer#192]
Hi,

I'd like to know if it's possible to customize the Share appearance with css using this project. I assume it would be done extending or overwriting themes, and I'd like to do it without having to deploy a JAR or AMP file.

Many thanks!

**Comment by aborroy** [comment]
You can tweak a bit the app using external resources, like in https://angelborroy.wordpress.com/2015/04/24/customizing-alfresco-for-demo-purposes/

But the AMP/JAR approach is always a better approach.
