### ISSUE TITLE
SMTP notification puts 8080 port onto address line

### ISSUE THREAD

**Issue by mantis1967** [Alfresco/alfresco-docker-installer#20]
I have Alfresco configured to use standard HTTP port  80, that is nginx listens on that port. All services inside the system are configured to be using 8080 port for intercommunication. Everything works fine, but when I receive notification from SMTP I get links with 8080 port inserted:
`http://r320:8080/share/page/user/12345/user-notifications`. Expected to have:
`http://r320/share/page/user/12345/user-notifications`. Any suggestions how to configure the port which is used here?

**Comment by aborroy** [comment]
This URL and port is taken from **alfresco-global.properties**, that are passed as params in **docker-compose.yml**:

```
                -Dshare.host=localhost
                -Dshare.port=80
```

These values should be like the following in your installation:

```
                -Dshare.host=r320
                -Dshare.port=80
```

**Comment by mantis1967** [comment]
@aborroy thanks for your suggestion. I will try to setup this configuration.

**Comment by mantis1967** [comment]
@aborroy thanks, that worked. However, I have another issue which I put into other thread.
