### ISSUE TITLE
javascript addon not included

### ISSUE THREAD

**Issue by SanjayBandhniya** [Alfresco/alfresco-docker-installer#205]
I am trying to create docker installer using latest version alfresco but javascript consolde add not getting included.
![image](https://github.com/user-attachments/assets/63322864-6e70-43bd-9aea-e851e47020a2)

I checked amps folder but there is not javascript console amps present.

**Comment by SanjayBandhniya** [comment]
Look like there is condition, if support-tools included the javascript console not include.

**Comment by douglascrp** [comment]
> Look like there is condition, if support-tools included the javascript console not include.

That is right, because ootb-support-tools now includes the javascript console functionality, there is no need to install it.

**Comment by SanjayBandhniya** [comment]
Thank you.
