### ISSUE TITLE
HTTPS connection configured

### ISSUE THREAD

**Issue by mantis1967** [Alfresco/alfresco-docker-installer#21]
When building docker images I select using HTTPS connection when answering to
`
 Do you want to use HTTPs for Web Proxy? 
`
thinking about further correct work of AOS (Microsoft Office editing from inside of the system). It works correctly, but at the same time I would like to allow users to connect to the system using HTTP. I achieve that having configured nginx to listen to both 80 and 443 ports. That works for content application, but not for the share. Share connection requires HTTPS anyway. Is it possible to fix that not having lost capabilities of editing documents with AOS?

Another question is when I receive a notification, it is configured with HTTP protocol and following the task link it requires me to authenticate within the system second time (first time with HTTPS). Is any way how to eliminate that?

**Comment by aborroy** [comment]
You can change Share host and port settings in `docker-compose.yml`:

https://github.com/Alfresco/alfresco-docker-installer/blob/master/generators/app/templates/6.2/docker-compose.yml#L32

`share.host` and `share.port` properties

**Comment by mantis1967** [comment]
Thanks, I will play with those and see if it helps.
