### ISSUE TITLE
possible issue with the javascript console ?

### ISSUE THREAD

**Issue by jpbuttet** [Alfresco/alfresco-docker-installer#22]
Hello,

Not sure this issue is related to the javascript console module or to the alfresco-docker-installer it self:

I can open the javascript console, can write some code but can't select the "run with folder (see attached screen capture).
Folder selection simply stays empty...

Does the javascript console on your reference install work well ?

Best regards.

Jean-Pierre

Some related logs , that show up few seconds after I use the javascript console:

2019-12-11 13:35:15,344  WARN  [alfresco.cache.contentUrlTransactionalCache] [http-nio-8080-exec-8] Transactional update cache 'org.alfresco.cache.contentUrlTransactionalCache' is full (65000).
share_1        |  2019-12-11 13:35:41,350  INFO  [webscripts.connector.RemoteClient] [http-nio-8080-exec-10] Exception calling (GET) http://alfresco:8080/alfresco/s/de/fme/jsconsole/serverInfo?alf_ticket=TICKET_84a083c2986a36409a53834552b21c486d3322c5
share_1        |  2019-12-11 13:35:41,370  INFO  [webscripts.connector.RemoteClient] [http-nio-8080-exec-10] Error status 408 Read timed out
share_1        |  java.net.SocketTimeoutException: Read timed out
......
.......
2019-12-11 13:36:03,675  WARN  [cache.node.nodesTransactionalCache] [http-nio-8080-exec-8] Transactional update cache 'org.alfresco.cache.node.nodesTransactionalCache' is full (125000).

![Capture_SelectFolder](https://user-images.githubusercontent.com/7593186/70626361-90164380-1c24-11ea-8256-05b3c31a43a6.JPG)

**Comment by aborroy** [comment]
That seems a problem of JSConsole:
https://github.com/share-extras/js-console/issues/80

**Comment by jpbuttet** [comment]
Hello,

Thank you for you answer and for the link.

Best regards.

**Comment by jpbuttet** [comment]
@aborroy 

I could see that this issue has been fixed back in december 2017:
https://github.com/share-extras/js-console/commit/4550446abdbbfc3280bb106d77ab4acde62380f4

I opened a bash in the share container and could see that the version of the file is:
10766 Oct 22  2013 javascript-console.get.head.ftl

I checked this file and could see that the line added in the fix was missing (line 8 in the fixed file):

<@script type="text/javascript" src="${page.url.context}/res/components/common/common-component-style-filter-chain.js"></@script>

Could this be the cause of the issue ?

Best regards.

**Comment by aborroy** [comment]
You're right, the change is not available in v0.6.0-rc1

https://github.com/share-extras/js-console/blob/v0.6.0-rc1/javascript-console-share/src/main/amp/config/alfresco/site-webscripts/de/fme/components/jsconsole/javascript-console.get.head.ftl

You can always use `master` branch, but probably adding this to alfresco-docker-installer is not an option.

**Comment by jpbuttet** [comment]
.... by the way, path of this file in the share container is:
tomcat/webapps/share/WEB-INF/classes/alfresco/site-webscripts/de/fme/components/jsconsole

Best reagards.

**Comment by jpbuttet** [comment]
okay, thanks
