### ISSUE TITLE
Postgres exit with weird message after a new installation

### ISSUE THREAD

**Issue by nevermind19** [Alfresco/alfresco-docker-installer#23]
With Ubuntu ,after all the steps did without any errors ...when i try to do the access from the web i have an error where told me the login isn't correct....i absolutely tried the login with admin and pass admin, but nothing happened always that error wrong username and password...
so i tried to understand cause i think is a problem from the database...
anyway i tried this command:

docker-compose images
         Container                     Repository                  Tag          Image Id      Size  
----------------------------------------------------------------------------------------------------
dockercompose_alfresco_1      dockercompose_alfresco          latest          62d37b43fa7f   2.27 GB
dockercompose_content-app_1   alfresco/alfresco-content-app   master-latest   c8cd3bd2d26c   30.9 MB
dockercompose_ocrmypdf_1      dockercompose_ocrmypdf          latest          8c4b2d669ce2   475 MB 
dockercompose_postgres_1      postgres                        10.1            ec61d13c8566   274 MB 
dockercompose_proxy_1         nginx                           stable-alpine   aaad4724567b   20.2 MB
dockercompose_share_1         dockercompose_share             latest          f5f086a8a452   720 MB 
dockercompose_solr6_1         dockercompose_solr6             latest          901eac40f922   1.03 GB

and after this command:
docker-compose ps
           Name                          Command               State          Ports       
------------------------------------------------------------------------------------------
dockercompose_alfresco_1      catalina.sh run -security        Up       8080/tcp          
dockercompose_content-app_1   /entrypoint.sh                   Up       80/tcp, 8080/tcp  
dockercompose_ocrmypdf_1      /usr/sbin/sshd -D                Up       22/tcp            
dockercompose_postgres_1      docker-entrypoint.sh postg ...   Exit 1                     
dockercompose_proxy_1         nginx -g daemon off;             Up       0.0.0.0:80->80/tcp
dockercompose_share_1         /usr/local/tomcat/shared/c ...   Up       8000/tcp, 8080/tcp
dockercompose_solr6_1         /bin/sh -c $DIST_DIR/solr/ ...   Up       8983/tcp          

and so the postgres is down....so i wanted to understand the logs and i had this answer:

docker-compose logs postgres
Attaching to dockercompose_postgres_1
postgres_1     | 2020-01-03 19:25:57.347 UTC [1] FATAL:  database files are incompatible with server
postgres_1     | 2020-01-03 19:25:57.347 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 10.1.

anyone can help me?

**Comment by mantis1967** [comment]
It clearly says that you are trying to use data prepared with Postgres 11 with Postgres 10.1 (your docker image is based on). 
1. Try Postgres image with version 11 mentioning it in docker-compose.yml instead of 10.1:

```
 postgres:
        image: postgres:11   #${POSTGRES_TAG}
```
2. Then rebuild:
`$ docker-compose up --build -d`
