### ISSUE TITLE
How to eliminate thumbnail/preview image stretching?

### ISSUE THREAD

**Issue by mantis1967** [Alfresco/alfresco-docker-installer#24]
Where in Alfresco image stretching can be fixed? Initial image is a circle:

- [Thumbnails generated](https://drive.google.com/file/d/1mb92H5JENdNYKiNGBd1W49rr08mX-1Ni/view?usp=sharing)
- [Preview generated](https://drive.google.com/file/d/1VTGOcTBjwjPh9B7hVi1H1ZeKbu6uJNpi/view?usp=sharing)

**Comment by aborroy** [comment]
I guess this is a CSS Share property. Not sure this can be configured.

**Comment by mantis1967** [comment]
So, are there any rules how to prepare images for Alfresco? Otherwise the use of alfresco as an image library would be problematic. It seems, I had no such issues with earlier version 5.2 if I am not mistaken.

**Comment by aborroy** [comment]
Not sure if that works different in current versions. Probably the best approach is to open an issue with your sample images in https://issues.alfresco.com/ to get a reply from Share Team.

**Comment by mantis1967** [comment]
@aborroy thanks.
