### ISSUE TITLE
Problem with using certbot for LetsEncrypt Cert

### ISSUE THREAD

**Issue by martinpetermichael** [Alfresco/alfresco-docker-installer#25]
Hello,,
first of all - thank you very much for this great work!
I got in trouble with using let's encrypt for getting ssl certs
I'm running into: 
`Failed authorization procedure. docs.xxxx.xx (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://docs.xxxxx.xx/.well-known/acme-challenge/`

```
 Domain: docs.xxxx.xx
   Type:   unauthorized
   Detail: Invalid response from
   http://docs.xxxx.xx/.well-known/acme-challenge/_ydSy1nPmzxSA5ol8jq2QHsagAA6AAZXbuIyUwOui8U
   [xx.xx.xx.xx]: 503
```

I used: 
`certbot certonly --standalone --agree-tos --cert-path /tmp/cert -d docs.xxxx.xx`
Also I turned of the nginx on my system, witch was blocking port 80.

Any clue how to solve?
Best regards
Martin

**Comment by aborroy** [comment]
It looks like a problem with NGINX redirection.

Can you access to http://docs.xxxxx.xx/.well-known/acme-challenge/ from your browser?

**Comment by martinpetermichael** [comment]
Hello,

sorry for beeing of for some times. Now I could solve the problem. I didn't  know why but nginx was installed (on premis) on my server - I purged it. Then
I did:

`certbot -d mydomain.domain.com`

then:

```
cd /etc/letsencrypt/live/mydomain/
cp fullchain1.pem /opt/docs/docker-compose/config/cert/localhost.cer
cp privkey.pem /opt/docs/docker-compose/config/cert/localhost.key
```
Restart of the container:

```
docker stop docker-compose_proxy_1
docker start docker-compose_proxy_1```

Optional - I wanted to have http redirected to https. For that I did:
in ../config/nginx.conf (at the end bevore the latest "}":

```
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name myserver.domain.com;
        return 301 https://$host$request_uri;
        }
```
and in the docker-compose.yml (section **proxy:**):

```
        ports:
            - 443:443
            - 80:80

```

Best regards
Martin
