### ISSUE TITLE
I can not see the button: "Create site"

### ISSUE THREAD

**Issue by nthphuong** [Alfresco/alfresco-docker-installer#27]
Dear Aborroy, 

Can you help me to config to show the button: "Create site" ?

Thanks so much!

**Comment by nthphuong** [comment]
> Dear Aborroy,
> 
> Can you help me to config to show the button: "Create site" ?
> 
> Thanks so much!

![1](https://user-images.githubusercontent.com/8097043/72331880-8b452380-36eb-11ea-96cb-f282b2873c95.png)

**Comment by aborroy** [comment]
If you installed https://github.com/jpotts/share-site-creators add-on, then you need to add users to group "GROUP_SITE_CREATORS". Only this users will be able to create sites.

**Comment by nthphuong** [comment]
Thanks, Aborroy.

**Comment by jpbuttet** [comment]
Had the same issue, thanks for the information

**Comment by nthphuong** [comment]
Resolved. Thanks.
