### ISSUE TITLE
Create site option is not coming in alfresco share.

### ISSUE THREAD

**Issue by kamendrpundr** [Alfresco/alfresco-docker-installer#28]
I installed alfresco 6.2 in ubuntu 18.04 and its running properly but im not getting create site option in user dashboard.

**Comment by aborroy** [comment]
See #27

**Comment by kamendrpundr** [comment]
what is overlays it is not recognizable by pom and how to install amps on alfresco content service 6.1 in alfresco/module/amps and share/module/amps folder?

**Comment by aborroy** [comment]
You need to add users to group "GROUP_SITE_CREATORS". Only this users will be able to create sites

**Comment by kamendrpundr** [comment]
![Screenshot from 2020-02-11 12-56-36](https://user-images.githubusercontent.com/52529023/74217666-1fe07880-4cce-11ea-883e-2ca4f365a823.png)
![Screenshot from 2020-02-11 12-57-07](https://user-images.githubusercontent.com/52529023/74217678-266ef000-4cce-11ea-80b8-e8d8b27ced2f.png)

**Comment by kamendrpundr** [comment]
Thank you @aborroy  for help
