### ISSUE TITLE
Got error when run: docker-compose up --build --force-recreate -d 

### ISSUE THREAD

**Issue by nthphuong** [Alfresco/alfresco-docker-installer#32]
Dear all,

I got the error as below when I run the command: docker-compose up --build --force-recreate -d 

![image](https://user-images.githubusercontent.com/8097043/75025345-9a2eab00-54cd-11ea-8ebd-58199c9bb5b5.png)

Please help me, thank you so much!

**The system info:**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

Docker version: 18.03.1-ce, build 9ee9f40
Node version: v10.19.0
npm version: 6.13.4

**Comment by aborroy** [comment]
It looks like there is some problem with the generation of the `docker-compose.yml`.

Can you provide the options you used for this generation?

Specially interested in the memory question.
