### ISSUE TITLE
Customizar Login in ADF

### ISSUE THREAD

**Issue by ofitecno** [Alfresco/alfresco-docker-installer#35]
Buenos dias, tengo hecha la instalacion de Alfresco Community mediante vuestro docker-compose. El funcionamiento es correcto pero me gustaria customizar el login del ADF, por lo que he visto se hace modificando un archivo:
https://www.alfresco.com/abn/adf/docs/tutorials/customising-login/
Archivo a modificar:   login.component.html
El problema es que no encuentro el archivo para crearle un Volume, entiendo que estará en el contenedor de la imagen --> alfresco/alfresco-content-app:master-latest
He intentado acceder al shell del contenedor pero da error:
docker exec -i -t [ID-CONTAINER] /bin/bash
Error  -->  
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

Me podeis decir como modifico el archivo necesario? mi idea era copiarlo del contenedor al host y hacer un volume al propio archivo de tal manera que los cambios se queden persistentes...

Gracias

**Comment by aborroy** [comment]
Ese container no tiene `bash` instalado.

Usa algo así como:

```
$ docker exec -it tmp_content-app_1 sh
```

Copia el archivo del contenedor y después podrás montar el volumen con los cambios que mencionas.

**Comment by ofitecno** [comment]
Cierto, he podido acceder por sh, pero tampoco está hay el archivo de personalizacion del login del ACA
¿Como lo puedo personalizar?, yo estaba probando con lo que dicen en el manual:
https://www.alfresco.com/abn/adf/docs/tutorials/customising-login/

**Comment by aborroy** [comment]
Para ese tipo de personalización, necesitarás compilar la aplicación a partir del código fuente y crear la imagen Docker.
