### ISSUE TITLE
Step 11/14 fails with "Could not resolve host: mirrorlist.centos.org/...."

### ISSUE THREAD

**Issue by aniellod** [Alfresco/alfresco-docker-installer#37]
Trying to install on Centos 8 host but running into apparent connectivity problem.

> Cannot find a valid baseurl for repo: base/7/x86_64
> Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
> 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
> ERROR: Service 'alfresco' failed to build: The command '/bin/sh -c yum -y update &&  yum -y install wget &&  yum clean all &&  set -x     && wget https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/api-explorer/${API_EXPLORER_TAG}/api-explorer-${API_EXPLORER_TAG}.war     -O /usr/local/tomcat/webapps/api-explorer.war' returned a non-zero code: 1

Included Dockerfile and docker-compose.yml
Let me know what other settings are needed.

[two-config-files.zip](https://github.com/Alfresco/alfresco-docker-installer/files/4576698/two-config-files.zip)

**Comment by aborroy** [comment]
It looks like your CentOS can't connect to "mirrorlist.centos.org". This is not related with the project, but with a CentOS issue.

**Comment by aniellod** [comment]
Thanks for the reply. Great that it's not related to the project. However I can connect fine to the mirror manually:

> [root@alfresco ~]# curl -L "http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra="
> http://mirror.it.ubc.ca/centos/7.8.2003/os/x86_64/
> http://centos.westmancom.com/7.8.2003/os/x86_64/
> http://mirror.its.sfu.ca/mirror/CentOS/7.8.2003/os/x86_64/
> http://mirror.esecuredata.com/centos/7.8.2003/os/x86_64/
> http://centos.mirror.ca.planethoster.net/7.8.2003/os/x86_64/
> http://centos.mirror.globo.tech/7.8.2003/os/x86_64/
> http://less.cogeco.net/CentOS/7.8.2003/os/x86_64/
> http://mirror.netaddicted.ca/CentOS/7.8.2003/os/x86_64/
> http://muug.ca/mirror/centos/7.8.2003/os/x86_64/
> http://centos.mirror.iweb.ca/7.8.2003/os/x86_64/

So it seems to be a problem within the container it created which I have no control over.

**Comment by aborroy** [comment]
It looks some network problem with Docker Containers. Can you run the same command inside the container?

**Comment by aniellod** [comment]
I can't connect to the container as it fails to startup. However, I've just tried using Ubuntu 20 and it worked fine and passed step 11. So there's something missing in Centos which makes it fail. You can close as the solution is to switch to a Ubuntu host.
Thanks :)

**Comment by aborroy** [comment]
Ok, thanks.

So the problem was using a CentOS host, but it's working fine with an Ubuntu one.

**Comment by Dnhatsave** [comment]
Hi, 
I've the same issue on my mac OS X, however if the solution is use ubuntu my question is how can i do to deploy it on Mac OS or centos OS, we cannot use another OS instead Ubuntu to install alfresco using docker??

**Comment by aborroy** [comment]
It looks like an intermittent failure on CentOS servers. I'm running successfully this configuration from Mac OS X daily.

**Comment by Dnhatsave** [comment]
well i'll try to change my mirror settings, its possible that some CentOS server mirrors are not available at my region
