### ISSUE TITLE
Best ideas on how to backup

### ISSUE THREAD

**Issue by aniellod** [Alfresco/alfresco-docker-installer#38]
I was able to install everything fine and can login using LDAP/SambaAD. It's wonderful (thanks Angel for the help). However, I'm not sure how to backup everything properly. Normally with non-Docker installs I can run BART (https://github.com/toniblyx/alfresco-backup-and-recovery-tool) but not sure how to do this with containers.
Any tips?

**Comment by aborroy** [comment]
I guess that saving "data" folder is enough, but I didn't test it. 

The only element that should require a different method is DB. You can use "pgdump" or so if that simple copy doesn't work.

**Comment by aniellod** [comment]
Will try testing a restore later but this works for backing the DB:
docker exec -t docker-compose_postgres_1 pg_dumpall -c -U alfresco > dump_`date +%Y-%m-%d"_"%H_%M_%S`.sql
