### ISSUE TITLE
How i can add LibreOffice into the docker?

### ISSUE THREAD

**Issue by nevermind19** [Alfresco/alfresco-docker-installer#42]
All work perfectly, but i can't see the preview of the document doc or docx or odt ....
How i can add into the docker LibreOffice for see the preview?

Thanks

**Comment by aborroy** [comment]
LibreOffice is provided by default:

https://github.com/Alfresco/alfresco-docker-installer/blob/master/generators/app/templates/6.2/docker-compose.yml#L110

Check this Docker Container is up and running in your composition.
