### ISSUE TITLE
Enterprise edition support

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-docker-installer#43]
Would be great if we could install enterprise edition with this.

**Comment by aborroy** [comment]
We have something similar for Enterprise in:
https://github.com/Alfresco/SearchServices/tree/master/e2e-test/generator-alfresco-docker-compose

I guess we could bring also Enterprise to this project.

**Comment by binduwavell** [comment]
I'm curious why you'd maintain multiple projects that are 90% the same?

**Comment by aborroy** [comment]
Just trying to hide some complexity to Community users. 
This project is oriented to people starting to use the product, while the other is oriented to test different configurations (mainly related with SOLR deployment) inside the team.

**Comment by binduwavell** [comment]
One way to hide the complexity is to have sane defaults and possibly to add more descriptive prompts. For generator-alfresco, each question has a mini set of documentation and a link to the actual documentation. As such it is both a tool for creating stuff and a resource to help people learn about the things they are creating. Many generated files even have comments that include links to documentation. Another thing we do is not ask questions if they are contra-indicated by a previous answer. If we start out by asking Community or Enterprise. And they select Community, we don't need to ask how many repository cluster nodes (contrived example). If they indicate Enterprise, we might want to ask how many cluster nodes to include.

I really like the idea of having someone run the generator and press enter/enter/enter/enter and bam, they get a useful starter project. However, if they look at each question and answer more selectively they are guided to create something that fits their needs very closely.

**Comment by aborroy** [comment]
Started a new project focused in Enterprise in 
https://github.com/aborroy/alfresco-enterprise-docker

**Comment by binduwavell** [comment]
Cool, thank you! In a way it would be ideal to combine the projects, but I take it that Alfresco does not want to be responsible the for enterprise version so you've moved it to your github account?

**Comment by aborroy** [comment]
Sorry, we moved that to https://github.com/AlfrescoLabs/alfresco-enterprise-docker
It's not officially supported, but it's part of the Alfresco ecosystem
