### ISSUE TITLE
Share Dockerfile is tight to the Server Name

### ISSUE THREAD

**Issue by naivoarevalo** [Alfresco/alfresco-docker-installer#50]
Hi,

As far I could see , the step _What is the name of your server?_ impacts over the Share DockerFile as follow:

`sed -i '/Connector port="8080"/a proxyName="myservername" proxyPort="443"' /usr/local/tomcat/conf/server.xml`

which _myservername_ is the answer to the above question.

Due to this, I need to change dockerfile manually according to the enviroment.

Is there a possibilty to modify this behaviour to be adapt it depending to the enviroment like the .env file in a docker-compose?

Thanks!

**Comment by aborroy** [comment]
I guess that impacts in some other files...

https://github.com/Alfresco/alfresco-docker-installer/commit/1127d6f26c311494d8859d3dea57d4be31a7fe5e#diff-384d5f6879b7e7207f87ff720f163e3e

You can build your own ".env" from the sources generated by this tool, but I'll evaluate if generating a ".env" file is something useful.

**Comment by naivoarevalo** [comment]
Hi aborroy, thanks for your answer.

I saw the commit, my humble opinion is changes in the _docker-compose_ and _.env_ are right because they makes sense in the _run_ docker stage.
In the other hand, the index.js file showed in the commit is not part of the generator output (in my case I could not see the file as result of the wizard)
My problem with the changes over the Share Dockerfile is that is not possible for me to _save_ the generator output files in my file store and then reuse them in other server only changing my .env file and since I perform some customization, the only way to make this works is run the wizard in each enviroment and makes the customization again.

I will try to change the /usr/local/tomcat/conf/server.xml file overriding the original using volumes and see what happen

Thanks again!

**Comment by naivoarevalo** [comment]
I share my proposal solution:

In Share Dockerfile I use a ARG with the Servername

`
ARG SERVER_NAME
sed -i "/Connector port=\"8080\"/a proxyName=\"${SERVER_NAME}\" proxyPort=\"443\"" /usr/local/tomcat/conf/server.xml
`

In my .env file
`
SERVER__NAME=servername
`

and finally in the docker-compose, share service section

`
args:
    SERVER_NAME: ${SERVER_NAME}
`

Regards

**Comment by aborroy** [comment]
Thanks for your contribution.

The feature is available from
https://github.com/Alfresco/alfresco-docker-installer/commit/d6e15c5aa2a96781db941b9672bcb202b83fdcbc
