### ISSUE TITLE
Check HTTPS endpoint in start.sh if encryption is used

### ISSUE THREAD

**Issue by otbutz** [Alfresco/alfresco-docker-installer#52]
https://github.com/Alfresco/alfresco-docker-installer/blob/8e77fd370cb04687323f2dccd431d9751bbc98e8/generators/app/templates/scripts/start.sh#L46

**Comment by aborroy** [comment]
Thanks again.

This change has been also added to latest version: https://github.com/Alfresco/alfresco-docker-installer/commit/7bcc5ab978d1d42e567f835357214dc95715bdab
