### ISSUE TITLE
No user management interface

### ISSUE THREAD

**Issue by RomanZemlyanukhin** [Alfresco/alfresco-docker-installer#53]
After the installation the admin page does not show the user management interface
How can I add the users?

**Comment by aborroy** [comment]
I can get access to that page.

![image](https://user-images.githubusercontent.com/48685308/94025749-2503bb00-fdb9-11ea-94fb-a8536ef64368.png)

What parameters are you using to build the Docker Compose template?

**Comment by RomanZemlyanukhin** [comment]
done
