### ISSUE TITLE
webdav problems

### ISSUE THREAD

**Issue by maxodoble** [Alfresco/alfresco-docker-installer#54]
hi,

tested today the latest release and generated alfresco 6.2 with proxy and ssl and server name test.example.com

seems to work ok, but i am getting problems with webdav:

* when trying to connect to webdav from linux/gnome/nautilus (url: davs://test.example.com/alfresco/webdav) i am getting a basic auth login window, where i am not asked for username/password but only for  a password: "Enter your password for Alfresco DAV ..."

* when exposing alfresco on port 8080 and connecting without proxy (url: dav://10.0.x.x:8080/alfresco/webdav) i am getting the correct login popup with username/password and i can login.

* when logged in, deleting, creating, renaming files is working o.k. moving a folder throws an error. trying to upload a file or folder from local disk: error: file exists.

* getting these errors not only with nautilus/gnome but with windows/carot dav client also.

any idea how to get rid of these problems?

**Comment by aborroy** [comment]
I guess these problems are mainly related with Linux systems:
https://docs.alfresco.com/community/concepts/troubleshoot-webdav.html

Not sure this project can help with that.

**Comment by maxodoble** [comment]
> I guess these problems are mainly related with Linux systems:
> https://docs.alfresco.com/community/concepts/troubleshoot-webdav.html

I've seen and read this "troubleshoot" document, and it has nothing to do with the problems i listed above - as far as i can tell.

I am getting problems with webdav with every os not just linux:

* linux and nginx proxy: no webdav login possible (gnome/Files)
* mac and nginx proxy: error on trying to login with webdav (Finder and cyberduck)
* win and nginx proxy: login is working. (carot dav)

* when not using the nginx proxy: webdav login is working on all os.

When logged in:

* NO upload of files/folders is possible: HTTP 302 (Found/redirect) -> and it stops there with "File exists". 
* Trying to duplicate content on webdav folder: endless loop of upload tries, but it's not working anyway.

There are by the way webdav clients that seem to work o.k even for the HTTP 302 situation:
* perl dave tool: with this tool you can upload folders and files correctly
* when directly mounting a webdav folder with davfs2 in linux: then the upload is also working.

So i was thinking there could be more problems here:

* Nginx Proxy possibly needs adjustments for webdav logins and functionality?
* Could a tomcat server.xml config update help? -> Connector ProxyName, proxyPort necessary if behind Proxy?
* Other config changes, that could influence webdav behaviour?

* Are there generally known webdav problems regarding upload of files/folders in Alfresco 6.2.0? 

The reason why i am asking here in this project:

* its the official alfresco docker generator, and i thought by using this project i will get a fully functional  docker install of alfresco 6.2.0-ga for testing purposes.
* If there are possibly config changes (nginx, tomcat, other?) needed for webdav it would benefit this project to integrate these changes, right?
* if it's a sole problem of the webdav implementation of core alfresco, it would be at least interesting to know the facts, and note them, in the readme/faqs of this project or so?

thank you,
Max

**Comment by aborroy** [comment]
I cannot replicate your problems.

On a quick test in Mac OS X with default configuration, everything seems to be working fine:

* Accessing https://test.example.com/alfresco/webdav is fine from the "Go > Connect to Server..." option and admin/admin credentials are accepted
* Files can be copied to the mounted drive
* Duplicating files can be done in the mounted drive

Not sure if you can give additional details on your problems. Anyway, you have all the code available to make your own tests with NGINX, Tomcat or whatever you want to customize.

Attached generated configuration for my test:
[alfresco-6.2-https-proxy.zip](https://github.com/Alfresco/alfresco-docker-installer/files/5339743/alfresco-6.2-https-proxy.zip)

**Comment by maxodoble** [comment]
hi,
i will try out your configuration today, and have a look what's different to my own.

i appreciate your looking into this,
thanks much.

**Comment by maxodoble** [comment]
hello again,

i tried your configuration and can confirm that the problems must be on my side.

will have to dig through whats different for me, because i tried to use almost no customization, but i must have overseen something in my config.

sorry for the noise,
and thanks very much for your input!
