### ISSUE TITLE
google-docs actions in documentlibrary always visible

### ISSUE THREAD

**Issue by maxodoble** [Alfresco/alfresco-docker-installer#55]
i can't seem to get rid of the google docs actions "create - google docs, spreadsheet, ..." in share.

set in alfresco global.properties:
`googledocs.enabled=false`

share-config-custom.xml (inside share container):

in this section:

~~~
<config evaluator="string-compare" condition="DocumentLibrary" replace="true">`
~~~

google-docs is disabled too:

~~~
<!--
         Google Docs™ integration
      -->
      <google-docs>
         <!--
            Enable/disable the Google Docs UI integration (Extra types on Create Content menu, Google Docs actions).
         -->
         <enabled>false</enabled>

         <!--
            The mimetypes of documents Google Docs allows you to create via the Share interface.
            The I18N label is created from the "type" attribute, e.g. google-docs.doc=Google Docs&trade; Document
         -->
         <creatable-types>
            <creatable type="doc">application/vnd.openxmlformats-officedocument.wordprocessingml.document</creatable>
            <creatable type="xls">application/vnd.openxmlformats-officedocument.spreadsheetml.sheet</creatable>
            <creatable type="ppt">application/vnd.ms-powerpoint</creatable>
         </creatable-types>
      </google-docs>
~~~

what am i missing here?

**Comment by aborroy** [comment]
Adding...

```
-Dgoogledocs.enabled=false
```

to `services.alfresco.environment.JAVA_OPTS` section in `docker-compose.yml` file works for me.

Did you try that?

**Comment by aborroy** [comment]
I've uploaded a new version with this add-on as optional.

**Comment by maxodoble** [comment]
thanks,

but out of curiosity:

what's the difference between setting a JAVA_OPTS env var:

~~~
-Dgoogledocs.enabled=false
~~~

and the same setting in a custom alfresco-global.properties (bind mounted inside container):

~~~
...
googledocs.enabled=false
...
~~~

shouldn't those two alternatives lead to the same outcome: "no google docs active"?

Max

**Comment by aborroy** [comment]
That will work always to you expose that Docker Volume to the outside. By default, the folder containing the `alfresco-global.properties` is not exposed, so your configuration has no effect on the repository.

**Comment by maxodoble** [comment]
frankly, i don't understand that 100%:

i have the alfresco-global.properties file exposed to the outside with a bind-mount in the docker-compose-file (ignore the "{{" stuff, that's coming from ansible-templating):

~~~
services:
  alfresco:
    build:
      context: ./alfresco
    mem_limit: 6464m
    container_name: {{ app_name }}_alfresco
    restart: unless-stopped
    environment:
      JAVA_OPTS : '
        -XX:+UseG1GC -XX:+UseStringDeduplication
        -Xms5952m -Xmx5952m   
      '
    volumes:
      - type: bind
        source: "{{ data_home }}/alf-data"
        target: "/usr/local/tomcat/alf_data"
      - type: bind
        source: "{{ data_home }}/alf-logs"
        target: "/usr/local/tomcat/logs"
      - type: bind
        source: "{{ app_home }}/alfresco/alfresco-global.properties"
        target: "/usr/local/tomcat/shared/classes/alfresco-global.properties"
      - type: bind
        source: "{{ app_home }}/alfresco/server.xml"
        target: "/usr/local/tomcat/conf/server.xml"
    ports:
      - 127.0.0.1:8080:8080
#      - 127.0.0.1:8008:8009
    networks:
      alfresco:
        ipv4_address: "{{ app_ip_alfresco }}"
~~~ 

when doing it this way, every setting in the exposed alfresco-global.properties (outside of the container) file should be working in the same way it would if using a JAVA_OPTS -D... setting? 

in the alfresco-global.properties outside of the container i am setting up everything i need, db, db-user, db-pwd and so on. this is working fine as far as i can see.

what didn't have any effect is the setting: `googledocs.enabled=false`. so that's why i am confused here.
