### ISSUE TITLE
google-docs actions in documentlibrary always visible

### ISSUE THREAD

**Issue by maxodoble** [Alfresco/alfresco-docker-installer#56]
Sorry to open a new issue here, but i couldn't reopen my closed [issue](https://github.com/Alfresco/alfresco-docker-installer/issues/55):

i've made a new test today with your latest version of alfresco-docker-installer (mostly default settings, no customizations)

~~~
yo alfresco-docker-installer
~~~

Have disabled google docs in the wizard and the generated docker-compose file shows correctly the setting:

~~~
-Dgoogledocs.enabled=false 
~~~

- Login to share
- Create new site
- Navigate to Document Library
- Click on "+ Create..."

And here i am still getting the links to the google docs stuff i wanted to get rid off:

![share_google_docs](https://user-images.githubusercontent.com/7969171/96745440-6db59080-13c6-11eb-8eaa-f0ed5c7afb29.png)

**Comment by aborroy** [comment]
It looks like "create-content" Surf element doesn't support evaluators:
https://github.com/Alfresco/google-docs/blob/V3.0.3/Google%20Docs%20Share/src/main/resources/META-INF/share-config-custom.xml#L76

As the AMP is deployed in Share web app directory (WAR deployment is not used) from default, it's not possible to uninstall properly the module.

**Comment by aborroy** [comment]
I've created a new "0.1.20" version that solves the problem uninstalling manually GoogleDocs Module from Share web application. 
Let me know if that works for you.

**Comment by maxodoble** [comment]
did a quick test with 0.1.20:

This is now working fine for me, no more links to google docs stuff visible!

And finally with your explanation from above (evaluators) i understand, why my attempts to disable these google-doc links  from within a custom alfresco-global.properties setting and additional settings in share-config-custom-dev.xml (with evaluators) didn't succeed.

Thank you very much, 
Max
