### ISSUE TITLE
access error

### ISSUE THREAD

**Issue by perenono69** [Alfresco/alfresco-docker-installer#57]
Hi,
   i have problem to launch installer, i have can deploy nodejs12, npm, yo ... with my root user. I launch with root user and i get : 

localhost:/opt/test_installer # yo alfresco-docker-installer
/usr/local/lib/node_modules/yo/node_modules/conf/index.js:128
                        throw err;
                        ^

Error: EACCES: permission denied, open '/root/.config/insight-nodejs/insight-yo.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Conf.get store [as store] (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:108:18)
    at Conf.get (/usr/local/lib/node_modules/yo/node_modules/conf/index.js:47:27)
    at Insight.get optOut [as optOut] (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:52:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:205:48)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/root/.config/insight-nodejs/insight-yo.json'
}

I have try to change user, change right to file, ... but no solution.
please help me

**Comment by aborroy** [comment]
Try using:

```
sudo npm install -g --unsafe-perm=true --allow-root
```

**Comment by perenono69** [comment]
I have try but error

localhost:/opt/test_installer # sudo npm install -g --unsafe-perm=true --allow-root
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-23T11_04_49_147Z-debug.log

After i have try in folder "/root/.config/insight-nodejs/" same error

**Comment by everbros** [comment]
Same here. It happens on Ubuntu Server 20 LTS. Any solution?
Steps to reproduce:
Fresh Ubuntu instance
```
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install -g yo
npm install --global generator-alfresco-docker-installer
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update	
sudo apt-get install docker-ce docker-ce-cli containerd.io

mkdir docker-compose
cd docker-compose

yo alfresco-docker-installer
```

**Comment by davidmuset** [comment]
You can not use 'yo' as root. You can create a new user to execute that command. Add 3 lines after install docker:

...
adduser alfresco
su alfresco
cd /home/alfresco

mkdir docker-compose
cd docker-compose

yo alfresco-docker-installer
