### ISSUE TITLE
question: csrf stuff

### ISSUE THREAD

**Issue by maxodoble** [Alfresco/alfresco-docker-installer#58]
i've noticed that you disable csrf with: `-Dcsrf.filter.enabled=false` by default.

why is that? is it not necessary any more here in this usecase?

i was used to (non docker deployment) enable csrf filtering in a share-config-custom.xml file like for example:

~~~
...
<config evaluator="string-compare" condition="CSRFPolicy" replace="true">
      <properties>
         <token>Alfresco-CSRFToken</token>
         <referer>https?:\/\/test.example.com\/.*</referer>
         <origin>https?:\/\/test.example.com.*</origin>
      </properties>
   </config>
...
~~~

Do i have to include such a setting to the share-config-custom-dev.xml file if i want csrf filtering to be active? (with replace="true")?

the default share-config-custom.xml file used in the share docker image does contain a longer list of stuff regarding to csrf settings. 
do i have to copy this stuff over to share-config-custom-dev.xml file too, if i use the above listed snippet, or to be safe against some csrf stuff in general?

Max

**Comment by aborroy** [comment]
A common configuration for CSRF is hard to be provided, but I could add this configuration to default templates if provided. This is why this project provides Docker Templates with CSRF filter disabled.

In order to add your custom configuration, using "share-config-custom.xml" or "share-config-custon-dev.xml" file is fine.

**Comment by maxodoble** [comment]
o.k.

is the snippet i listed above sufficient for preventing csrf problems, or are there additional settings that have to be considered?
