### ISSUE TITLE
Help needed : Solr UnknownHostException

### ISSUE THREAD

**Issue by FlorahC** [Alfresco/alfresco-docker-installer#59]
I just need help. I don't know if it's my local environment but I am struggling to get a running application.
Solr keeps throwing these errors 

`2020-11-01 22:22:10.026 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@648ee871_Worker-9) [ ] o.a.s.t.ShardStatePublisher Unable to publish this node state. A failure condition has been met during the outbound subscription message encoding process. See the stacktrace below for further details.
java.net.UnknownHostException: alfresco`

I followed the read me instructions. Up until the section **Docker Volumes**  When I go beyond that section I get operation not permitted errors so I changed back the ownership

Can I get help on this? How can I get solr working please. I just need a running app. Please see my solr yml config below

`solr6:
        build:
          context: ./search
          args:
            SEARCH_TAG: $SEARCH_CE_TAG
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: localhost
            ALFRESCO_COMMS: none
            CROSS_LOCALE: "true"
        mem_limit: 1184m
        environment:
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8080"
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms928m -Xmx928m"
            SOLR_OPTS: "
                -XX:NewSize=336m
                -XX:MaxNewSize=336m
            "
        volumes: 
            - ./data/solr-data:/opt/alfresco-search-services/data  `

**Comment by aborroy** [comment]
It’s Alfresco the service that is not working. SOLR is complaining because Alfresco is down. Check the logs to find out why Alfresco service is not starting.

**Comment by FlorahC** [comment]
All I see are info and warn logs on the alfresco container logs.

`NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
02-Nov-2020 21:00:25.027 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.34
02-Nov-2020 21:00:25.047 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 4 2018 22:28:22 UTC
02-Nov-2020 21:00:25.048 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.34.0
02-Nov-2020 21:00:25.049 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Nov-2020 21:00:25.066 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.39-linuxkit
02-Nov-2020 21:00:25.069 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Nov-2020 21:00:25.071 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/java/jdk-11.0.1
02-Nov-2020 21:00:25.075 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.1+13
02-Nov-2020 21:00:25.079 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
02-Nov-2020 21:00:25.081 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
02-Nov-2020 21:00:25.083 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
02-Nov-2020 21:00:25.085 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
02-Nov-2020 21:00:25.089 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
02-Nov-2020 21:00:25.091 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
02-Nov-2020 21:00:25.093 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
02-Nov-2020 21:00:25.095 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Nov-2020 21:00:25.099 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.username=alfresco
02-Nov-2020 21:00:25.103 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.password=alfresco
02-Nov-2020 21:00:25.105 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.driver=org.postgresql.Driver
02-Nov-2020 21:00:25.106 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
02-Nov-2020 21:00:25.111 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsolr.host=solr6
02-Nov-2020 21:00:25.112 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsolr.secureComms=none
02-Nov-2020 21:00:25.113 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsolr.baseUrl=/solr
02-Nov-2020 21:00:25.116 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dindex.subsystem.name=solr6
02-Nov-2020 21:00:25.119 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dalfresco.host=localhost
02-Nov-2020 21:00:25.121 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dalfresco.port=80
02-Nov-2020 21:00:25.122 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dshare.host=localhost
02-Nov-2020 21:00:25.125 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dshare.port=80
02-Nov-2020 21:00:25.130 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Daos.baseUrlOverwrite=http://localhost/alfresco/aos
02-Nov-2020 21:00:25.132 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddeployment.method=DOCKER_COMPOSE
02-Nov-2020 21:00:25.132 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcsrf.filter.enabled=false
02-Nov-2020 21:00:25.133 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dopencmis.server.override=true
02-Nov-2020 21:00:25.134 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dopencmis.server.value=http://localhost:80
02-Nov-2020 21:00:25.134 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dalfresco.restApi.basicAuthScheme=true
02-Nov-2020 21:00:25.135 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dmessaging.subsystem.autoStart=false
02-Nov-2020 21:00:25.136 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dauthentication.protection.enabled=false
02-Nov-2020 21:00:25.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC
02-Nov-2020 21:00:25.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseStringDeduplication
02-Nov-2020 21:00:25.139 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms3904m
02-Nov-2020 21:00:25.139 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx3904m
02-Nov-2020 21:00:25.140 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
02-Nov-2020 21:00:25.143 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Nov-2020 21:00:25.145 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
02-Nov-2020 21:00:25.146 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
02-Nov-2020 21:00:25.147 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.manager
02-Nov-2020 21:00:25.147 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.policy==/usr/local/tomcat/conf/catalina.policy
02-Nov-2020 21:00:25.148 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
02-Nov-2020 21:00:25.148 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
02-Nov-2020 21:00:25.149 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
02-Nov-2020 21:00:25.150 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.17] using APR version [1.4.8].
02-Nov-2020 21:00:25.150 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
02-Nov-2020 21:00:25.154 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
02-Nov-2020 21:00:25.196 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.2k-fips  26 Jan 2017]
02-Nov-2020 21:00:25.531 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
02-Nov-2020 21:00:25.610 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
02-Nov-2020 21:00:25.642 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
02-Nov-2020 21:00:25.650 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
02-Nov-2020 21:00:25.653 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 3035 ms
02-Nov-2020 21:00:26.017 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
02-Nov-2020 21:00:26.018 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.34
02-Nov-2020 21:00:26.180 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/api-explorer.war]
02-Nov-2020 21:00:28.603 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Nov-2020 21:00:30.930 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/api-explorer.war] has finished in [4,745] ms
02-Nov-2020 21:00:30.936 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/alfresco]
02-Nov-2020 21:00:34.597 WARNING [localhost-startStop-1] org.apache.juli.ClassLoaderLogManager.readConfiguration Reading /usr/local/tomcat/webapps/alfresco/WEB-INF/classes/logging.properties is not permitted. See "per context logging" in the default catalina.policy file.
02-Nov-2020 21:01:14.565 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-11-02 21:01:35,696  INFO  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Ignoring script patch (post-Hibernate): patch.db-V4.2-metadata-query-indexes
 2020-11-02 21:01:35,701  INFO  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Ignoring script patch (post-Hibernate): patch.db-V5.1-metadata-query-indexes
 2020-11-02 21:01:35,701  INFO  [domain.schema.SchemaBootstrap] [localhost-startStop-1] Ignoring script patch (post-Hibernate): patch.db-V5.2-remove-jbpm-tables-from-db
 2020-11-02 21:01:36,147  INFO  [alfresco.repo.admin] [localhost-startStop-1] Using database URL 'jdbc:postgresql://postgres:5432/alfresco' with user 'alfresco'.
 2020-11-02 21:01:36,148  INFO  [alfresco.repo.admin] [localhost-startStop-1] Connected to database PostgreSQL version 10.1
 NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
02-Nov-2020 21:03:15.361 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.34
02-Nov-2020 21:03:15.366 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 4 2018 22:28:22 UTC
02-Nov-2020 21:03:15.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.34.0
02-Nov-2020 21:03:15.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
02-Nov-2020 21:03:15.367 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.39-linuxkit
02-Nov-2020 21:03:15.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
02-Nov-2020 21:03:15.368 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/java/jdk-11.0.1
02-Nov-2020 21:03:15.369 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.1+13
02-Nov-2020 21:03:15.370 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
02-Nov-2020 21:03:15.370 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
02-Nov-2020 21:03:15.371 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
02-Nov-2020 21:03:15.372 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
02-Nov-2020 21:03:15.372 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
02-Nov-2020 21:03:15.372 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
02-Nov-2020 21:03:15.373 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
02-Nov-2020 21:03:15.373 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
02-Nov-2020 21:03:15.374 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.username=alfresco
02-Nov-2020 21:03:15.374 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.password=alfresco
02-Nov-2020 21:03:15.374 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.driver=org.postgresql.Driver
02-Nov-2020 21:03:15.375 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
02-Nov-2020 21:03:15.376 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsolr.host=solr6
02-Nov-2020 21:03:15.376 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsolr.secureComms=none
02-Nov-2020 21:03:15.376 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsolr.baseUrl=/solr
02-Nov-2020 21:03:15.377 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dindex.subsystem.name=solr6
02-Nov-2020 21:03:15.377 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dalfresco.host=localhost
02-Nov-2020 21:03:15.378 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dalfresco.port=80
02-Nov-2020 21:03:15.378 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dshare.host=localhost
02-Nov-2020 21:03:15.379 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dshare.port=80
02-Nov-2020 21:03:15.379 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Daos.baseUrlOverwrite=http://localhost/alfresco/aos
02-Nov-2020 21:03:15.379 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ddeployment.method=DOCKER_COMPOSE
02-Nov-2020 21:03:15.380 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcsrf.filter.enabled=false
02-Nov-2020 21:03:15.380 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dopencmis.server.override=true
02-Nov-2020 21:03:15.381 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dopencmis.server.value=http://localhost:80
02-Nov-2020 21:03:15.381 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dalfresco.restApi.basicAuthScheme=true
02-Nov-2020 21:03:15.381 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dmessaging.subsystem.autoStart=false
02-Nov-2020 21:03:15.382 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dauthentication.protection.enabled=false
02-Nov-2020 21:03:15.382 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC
02-Nov-2020 21:03:15.383 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseStringDeduplication
02-Nov-2020 21:03:15.383 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms3904m
02-Nov-2020 21:03:15.383 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx3904m
02-Nov-2020 21:03:15.384 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
02-Nov-2020 21:03:15.384 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
02-Nov-2020 21:03:15.384 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
02-Nov-2020 21:03:15.385 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
02-Nov-2020 21:03:15.385 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.manager
02-Nov-2020 21:03:15.385 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.policy==/usr/local/tomcat/conf/catalina.policy
02-Nov-2020 21:03:15.386 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
02-Nov-2020 21:03:15.386 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
02-Nov-2020 21:03:15.387 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
02-Nov-2020 21:03:15.387 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.17] using APR version [1.4.8].
02-Nov-2020 21:03:15.387 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
02-Nov-2020 21:03:15.388 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
02-Nov-2020 21:03:15.400 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.2k-fips  26 Jan 2017]
02-Nov-2020 21:03:15.492 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
02-Nov-2020 21:03:15.522 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
02-Nov-2020 21:03:15.534 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
02-Nov-2020 21:03:15.537 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
02-Nov-2020 21:03:15.538 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 907 ms
02-Nov-2020 21:03:15.623 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
02-Nov-2020 21:03:15.623 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.34
02-Nov-2020 21:03:15.681 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/api-explorer.war]
02-Nov-2020 21:03:16.389 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
02-Nov-2020 21:03:16.478 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/api-explorer.war] has finished in [797] ms
02-Nov-2020 21:03:16.481 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/alfresco]
02-Nov-2020 21:03:17.169 WARNING [localhost-startStop-1] org.apache.juli.ClassLoaderLogManager.readConfiguration Reading /usr/local/tomcat/webapps/alfresco/WEB-INF/classes/logging.properties is not permitted. See "per context logging" in the default catalina.policy file.`

Below is what I am getting from the proxy

`2020/11/02 21:03:15 [error] 15#15: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"

172.18.0.1 - - [02/Nov/2020:21:03:15 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

2020/11/02 21:03:36 [error] 15#15: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"

2020/11/02 21:03:36 [error] 15#15: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"

172.18.0.1 - - [02/Nov/2020:21:03:36 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

172.18.0.1 - - [02/Nov/2020:21:03:36 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

172.18.0.1 - - [02/Nov/2020:21:04:05 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

172.18.0.1 - - [02/Nov/2020:21:04:05 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

2020/11/02 21:04:05 [error] 15#15: *9 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"`

**Comment by FlorahC** [comment]
Below is what I am getting from the proxy

```2020/11/02 21:03:15 [error] 15#15: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"

172.18.0.1 - - [02/Nov/2020:21:03:15 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

2020/11/02 21:03:36 [error] 15#15: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"

2020/11/02 21:03:36 [error] 15#15: *5 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"

`172.18.0.1 - - [02/Nov/2020:21:03:36 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

172.18.0.1 - - [02/Nov/2020:21:03:36 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

172.18.0.1 - - [02/Nov/2020:21:04:05 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

172.18.0.1 - - [02/Nov/2020:21:04:05 +0000] "HEAD /alfresco/ HTTP/1.1" 502 0 "-" "axios/0.19.2"

2020/11/02 21:04:05 [error] 15#15: *9 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.18.0.1, server: , request: "HEAD /alfresco/ HTTP/1.1", upstream: "http://172.18.0.2:8080/alfresco/", host: "localhost"```

**Comment by aborroy** [comment]
How many RAM are you using for Docker?

**Comment by FlorahC** [comment]
Oh my goodness. You're amazing!! That worked. I increased docker to 8g from 2g. Argh. Thank you!! Thank you so much
