### ISSUE TITLE
Ocrmypdf not work

### ISSUE THREAD

**Issue by edutonelli** [Alfresco/alfresco-docker-installer#6]
Hi, i click on OCR option and do not work. See the message below from log:

alfresco_1               | Exception in thread "defaultAsyncAction3" java.lang.RuntimeException: java.lang.RuntimeException: org.alfresco.service.cmr.repository.ContentIOException: 08200037 Failed to copy content from file:
alfresco_1               |    writer: ContentAccessor[ contentUrl=store://2019/9/20/23/7/99d27ddc-638d-42ef-b8e6-3a6fd0be0c1a.bin, mimetype=application/pdf, size=0, encoding=UTF-8, locale=en_US]
alfresco_1               |    file: /usr/local/tomcat/temp/Alfresco/OCRTransformWorker_source_2056705859773778016_ocr.pdf
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction.executeImplInternal(OCRExtractAction.java:183)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction.access$200(OCRExtractAction.java:38)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction$1.execute(OCRExtractAction.java:164)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction$1.execute(OCRExtractAction.java:161)
alfresco_1               |      at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction.executeInNewTransaction(OCRExtractAction.java:169)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction.access$100(OCRExtractAction.java:38)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction$ExtractOCRTask.run(OCRExtractAction.java:151)
alfresco_1               |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
alfresco_1               |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
alfresco_1               |      at java.base/java.lang.Thread.run(Thread.java:834)
alfresco_1               | Caused by: java.lang.RuntimeException: org.alfresco.service.cmr.repository.ContentIOException: 08200037 Failed to copy content from file:
alfresco_1               |    writer: ContentAccessor[ contentUrl=store://2019/9/20/23/7/99d27ddc-638d-42ef-b8e6-3a6fd0be0c1a.bin, mimetype=application/pdf, size=0, encoding=UTF-8, locale=en_US]
alfresco_1               |    file: /usr/local/tomcat/temp/Alfresco/OCRTransformWorker_source_2056705859773778016_ocr.pdf
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRTransformWorker.transform(OCRTransformWorker.java:86)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRExtractAction.executeImplInternal(OCRExtractAction.java:181)
alfresco_1               |      ... 10 more
alfresco_1               | Caused by: org.alfresco.service.cmr.repository.ContentIOException: 08200037 Failed to copy content from file:
alfresco_1               |    writer: ContentAccessor[ contentUrl=store://2019/9/20/23/7/99d27ddc-638d-42ef-b8e6-3a6fd0be0c1a.bin, mimetype=application/pdf, size=0, encoding=UTF-8, locale=en_US]
alfresco_1               |    file: /usr/local/tomcat/temp/Alfresco/OCRTransformWorker_source_2056705859773778016_ocr.pdf
alfresco_1               |      at org.alfresco.repo.content.AbstractContentWriter.putContent(AbstractContentWriter.java:491)
alfresco_1               |      at es.keensoft.alfresco.ocr.OCRTransformWorker.transform(OCRTransformWorker.java:83)
alfresco_1               |      ... 11 more
alfresco_1               | Caused by: java.io.FileNotFoundException: /usr/local/tomcat/temp/Alfresco/OCRTransformWorker_source_205670585977377801

**Comment by Wellstat-tech** [comment]
Same problem here, after working through other permissions issues it looks like everything but OCR works.  I suspect it is another permissions issue but I haven't found a solution yet.

**Comment by aborroy** [comment]
What operating system are you using?

**Comment by Wellstat-tech** [comment]
Centos 7

**Comment by aborroy** [comment]
Hope this helps to understand how to set your permissions: https://medium.com/@nielssj/docker-volumes-and-file-system-permissions-772c1aee23ca

I’ll try to write down some customised guide for this task or to provide alternatives to host volumes.
