### ISSUE TITLE
exposing tomcat to host

### ISSUE THREAD

**Issue by delacosta456** [Alfresco/alfresco-docker-installer#61]
hi
Please can somebody help me on how to expose tomcat container's file to host

Thanks

**Comment by aborroy** [comment]
What 'tomcat container's file' means?

**Comment by delacosta456** [comment]
hi
sorry i mean any way to expose the tomcat forder to host ? I need to access files inside for customization...

i need to access all files as if it was install maually (distribution.zip)

**Comment by aborroy** [comment]
Docker does not work in that way. I suggest you to use ZIP Distribution file instead.

**Comment by delacosta456** [comment]
ok thanks
