### ISSUE TITLE
admin default password in 7.0 ?

### ISSUE THREAD

**Issue by mvbiop** [Alfresco/alfresco-docker-installer#69]
I just installed ACS 7.0 with this installer, fresh, empty install. 

However, logging with the usual admin/admin credentials fails?!

With the previous version 6.2, this worked, but now? Has anything changed?

Thanks in advance for any help!

**Comment by aborroy** [comment]
Can you attach the options you selected and the produced `docker-compose.yml` file?

**Comment by mvbiop** [comment]
Thanks, sure!

I noticed, by the way, that the database is empty (pg_dump on container shell...)?  

[docker-compose.yml.txt](https://github.com/Alfresco/alfresco-docker-installer/files/6213670/docker-compose.yml.txt)

**Comment by aborroy** [comment]
Do you have 64 GB RAM allocated for Docker?

**Comment by mvbiop** [comment]
Yes, the machine has lots of memory, and the containers start up with no problem. I read in another forum that the postgres version might be a problem, so I tried with 11.7 instead 13.1, but no luck. Time permitting I'll investigate a bit more. Thanks again for your help.

**Comment by infinite-dao** [comment]
Just an idea, I had a similar problem testing locally with 6.2 before and, after setting correct the group rights also for the `data/postgres-data` folder the login worked. Because, as I understand it, the user login data are retrieved from PostgreSQL database (and so it depends on this postgres container setup or Dockefile settings or entry-point.sh stuff etc. or what it can read or can not read from it)

See perhaps https://github.com/Alfresco/alfresco-docker-installer#docker-volumes and what is described in detail for setting group rights for `solr-data`, this has perhaps to be done in an analogous way for PostgreSQL data directory / log directory etc..

**Comment by infinite-dao** [comment]
> Just an idea, I had a similar problem testing locally with 6.2 before and, after setting correct the group rights also for the `data/postgres-data` folder the login worked. Because, as I understand it, the user login data are retrieved from PostgreSQL database (and so it depends on this postgres container setup or Dockefile settings or entry-point.sh stuff etc. or what it can read or can not read from it)

I have the same issue now (login as admin does not work) … well, after I solved initial group rights problems for postgres …
```bash
# in my case
sudo chown -R 999 /path/to/alfresco-docker-compose/logs/postgres
sudo chown -R 999 /path/to/alfresco-docker-compose/data/postgres-data
```
… and emptying my initial postgres database (mishmash), starting up `docker-compose up -d` the postgres database gets created correctly and postgres logging works, but the network traffic console log shows a 404 Not Found Error internally upon log in as admin:
```
proxy_1 … "POST /alfresco/api/-default-/public/authentication/versions/1/tickets HTTP/1.1" 404
```
… but I have no clue yet where the very first error originates from that leads to the login failure.

In my case I have limited 8GB RAM that could be entangled with it as well. I will try the 6.2 version if I do not find a solution in 7.0.

**Comment by infinite-dao** [comment]
> In my case I have limited 8GB RAM that could be entangled with it as well. I will try the 6.2 version if I do not find a solution in 7.0.

I gave up on 7.0 but 6.2 works as expected. By the way, if one uses volumes for solr6 and postgres one can prepare  beforehand empty data directories only for volumes of `solr6`, `postgres` (logs and data directory), then the _very first_ `docker-compose up --build --force-recreate --detach` can run successful for logging in; I did prepare those empty directories like so:

```bash
# preparation of postgres volumes (group rights known from previous testing)
sudo mkdir --parents /opt/alfresco-docker-compose/data/postgres-data
sudo chown -R 999 /opt/alfresco-docker-compose/data/postgres-data
sudo mkdir --parents /opt/alfresco-docker-compose/logs/postgres
sudo chown -R 999 /opt/alfresco-docker-compose/logs/postgres

# preparation of solr-data volumes (group rights known from previous testing)
sudo mkdir --parents /opt/alfresco-docker-compose/data/solr-data
sudo chown -R 33007 /opt/alfresco-docker-compose/data/solr-data
```

<hr/>

> mvbiop … Time permitting I'll investigate a bit more. …

@mvbiop regarding [your #issuecomment-812037411](https://github.com/Alfresco/alfresco-docker-installer/issues/69#issuecomment-812037411) have you found out more for solving this issue in Alfresco 7.0 ?

**Comment by a42niem** [comment]
The postgres logfile shows: FATAL:  database "alfresco" does not exist
Restart does not help and also not my trying to manually create the database.
So I decided to downgrade postgres to 11.4 which is working in Alfresco 6.2:
- stop Alfresco
- delete all content in data/postgres-data
- edit line in file .env to "POSTGRES_TAG=11.4"
- run start.sh 

The lines with 404 are gone and after some time it finishes.

Folders data/alf-repo-data and data/solr-data are populated and login to Alfresco works as expected

**Comment by aborroy** [comment]
Can you attach the failing `docker-compose.yml` file?

**Comment by a42niem** [comment]
Here it is 
[docker-compose.yml.txt](https://github.com/Alfresco/alfresco-docker-installer/files/6334348/docker-compose.yml.txt)

**Comment by aborroy** [comment]
That worked without any issues from Mac using following env file

```
# Docker Image versions
ALFRESCO_CE_TAG=7.0.0
SEARCH_CE_TAG=2.0.1
SHARE_TAG=7.0.0
ACA_TAG=2.3.0
POSTGRES_TAG=13.1
API_EXPLORER_TAG=7.0.0
TRANSFORM_ENGINE_TAG=2.3.10
ACTIVEMQ_TAG=5.16.1
```

What host OS are you using?

**Comment by a42niem** [comment]
I am on Devuan beowulf, which is Debian Buster without systemd. Docker is 18.09.1 and docker-compose is 1.21.0 if that helps

**Comment by infinite-dao** [comment]
Now I tried once more CE 7.0 and it worked “somehow”—although not at the first start up. 

Here is what I did in detail:

1. before running `docker-compose up --build --force-recreate --detach` I did:
    - first I had prepared postgres directories (as described [#issuecomment-820305976](https://github.com/Alfresco/alfresco-docker-installer/issues/69#issuecomment-820305976) above)
    - I modified also solr6 admin `nginx.htpasswd` with `htpasswd` tool (see perhaps https://github.com/aborroy/acs-proxy/issues/3)
    - I altered `Dmetadata-keystore.password` and `Dmetadata-keystore.metadata.password` (this probably stopped me from login as admin to the my-server-site/share)
2. after realising an unsuccessful log in as admin I read log messages like `Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect`, so (1) I stopped docker: `docker-compose down`, (2) altered passwords to have the default values  for `Dmetadata-keystore.password` and `Dmetadata-keystore.metadata.password`
3. running again `docker-compose up --build --force-recreate --detach` did succeed in logging in as admin with default password admin

**Comment by Jonbj** [comment]
Any news on this Issue?

**Comment by infinite-dao** [comment]
> Any news on this Issue?

I have installed today (2021-06-09) another Alfrecso 7.0 instance and I could log in as admin with password admin. So from my point of view it is working as expected now.

**Comment by saipasha** [comment]
I just installed the Alfresco 7.0 with no apparent setbacks and I can't log in as admin. Not sure if this was temporarily fixed or there's a missing config. Any news? (2021-07-16)

**Comment by aborroy** [comment]
You need to explore your logs, in order to understand if Alfresco Repository started.
Or you can try http://localhost/alfresco instead of http://localhost/share
You need both services in order to get the platform working.
