### ISSUE TITLE
Problem ubuntu Step 11/14 

### ISSUE THREAD

**Issue by daeynasvistas** [Alfresco/alfresco-docker-installer#7]
have problem with ubuntu install.. do i need centOS for this?

`Step 11/14 : RUN yum -y update &&  yum -y install wget &&  yum clean all &&  set -x     && wget https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/api-explorer/${API_EXPLORER_TAG}/api-explorer-${API_EXPLORER_TAG}.war     -O /usr/local/tomcat/webapps/api-explorer.war`

`ERROR: Service 'alfresco' failed to build: The command '/bin/sh -c yum -y update &&  yum -y install wget &&  yum clean all &&  set -x     && wget https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/api-explorer/${API_EXPLORER_TAG}/api-explorer-${API_EXPLORER_TAG}.war     -O /usr/local/tomcat/webapps/api-explorer.war' returned a non-zero code: 1`

command:  docker-compose up --build --force-recreate -d

**Comment by aborroy** [comment]
Centos is used inside the Docker Images, probably this error is due to a connection error.

**Comment by aborroy** [comment]
If you used default API_EXPLORER_TAG in .env file, this should be downloading URL:

https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/api-explorer/6.1.0/api-explorer-6.1.0.war

Have you access to this URL?

**Comment by praveenpks** [comment]
I am also getting this error. Has anyone found any solution.

**Comment by Dnhatsave** [comment]
I got the same error on Mac OS posted at #37

**Comment by Dnhatsave** [comment]
Hi, 
Today i got the same error on ubuntu 

` 14e53a558408
Step 11/15 : RUN yum -y update &&  yum -y install wget &&  yum clean all &&  set -x     && wget https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/api-explorer/${API_EXPLORER_TAG}/api-explorer-${API_EXPLORER_TAG}.war     -O /usr/local/tomcat/webapps/api-explorer.war
 ---> Running in 1dfc56aedb67
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: repos-jnb.psychz.net
 * extras: repos-jnb.psychz.net
 * updates: repos-jnb.psychz.net
http://repos-jnb.psychz.net/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://jnb.mirror.kvm.net/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://mirror.ufs.ac.za/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://mirror.retentionrange.co.bw/centOS/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://centos.hqserv.co.il/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://mirror.wiru.co.za/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://www.ftp.saix.net/linux/distributions/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://centos.mirror.liquidtelecom.com/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://centos.activecloud.co.il/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.
http://mirror.aptus.co.tz/pub/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
Trying other mirror.


 One of the configured repositories failed (CentOS-7 - Base),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=base ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable base
        or
            subscription-manager repos --disable=base

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=base.skip_if_unavailable=true

failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://repos-jnb.psychz.net/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://jnb.mirror.kvm.net/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://mirror.ufs.ac.za/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://mirror.retentionrange.co.bw/centOS/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://centos.hqserv.co.il/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://mirror.wiru.co.za/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://www.ftp.saix.net/linux/distributions/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://centos.mirror.liquidtelecom.com/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://centos.activecloud.co.il/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
http://mirror.aptus.co.tz/pub/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#52 - "Empty reply from server"
ERROR: Service 'alfresco' failed to build: The command '/bin/sh -c yum -y update &&  yum -y install wget &&  yum clean all &&  set -x     && wget https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/api-explorer/${API_EXPLORER_TAG}/api-explorer-${API_EXPLORER_TAG}.war     -O /usr/local/tomcat/webapps/api-explorer.war' returned a non-zero code: 1
`

docker comand: **sudo docker-compose build --no-cache && docker-compose up -d --force-recreate**

**Comment by melani016** [comment]
got same error. has anyone solved this?
