### ISSUE TITLE
Changes via UI become blocked after short period of time

### ISSUE THREAD

**Issue by techabilla** [Alfresco/alfresco-docker-installer#72]
If I build fresh containers (& volumes), I can happily create Users, Files, Folders etc. After a while though (maybe a day or so), I can no longer make any changes via the UI. Changes via the API still appear to work. I'm running V7 on Docker Desktop for Windows, but have the same issue on V6.2.

**Comment by aborroy** [comment]
Can you attach your docker-compose.yml file?
What UI are you using? Share or ACA?
