### ISSUE TITLE
Alfresco 7 (repository not working)

### ISSUE THREAD

**Issue by SanjayBandhniya** [Alfresco/alfresco-docker-installer#73]
I am using alfresco docker installer for alfresco 6.2 and it is working.
Same way I trued with alfresco 7 but it is not working.
Logs folder is also not creating.
I am using window OS.

Below are the errors.

| 2021-04-18 03:25:00.054 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@69eb86b4_Worker-36) [   ] o.a.s.t.AbstractTracker [alfresco / MODEL@2053669411 / IT #1618716300049] Tracking failure. See the stacktrace below for further details.
solr6_1               | org.alfresco.error.AlfrescoRuntimeException: 03180043 api/solr/modelsdiff return status:404
solr6_1               |         at org.alfresco.solr.client.SOLRAPIClient.callRepository(SOLRAPIClient.java:1596)
solr6_1               |         at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1103)
solr6_1               |         at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:313)
solr6_1               |         at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:275)
solr6_1               |         at org.alfresco.solr.tracker.ModelTracker.doTrack(ModelTracker.java:235)
solr6_1               |         at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:242)
solr6_1               |         at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:60)
solr6_1               |         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
solr6_1               |         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
solr6_1               | 2021-04-18 03:25:00.061 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@69eb86b4_Worker-33) [   ] o.a.s.t.AbstractTracker [archive / NODE_STATE_PUBLISHER@92181297 / IT #1618716300051] Tracking failure. See the stacktrace below for further details.
solr6_1               | org.alfresco.error.AlfrescoRuntimeException: 03180044 GetTransactions return status is 404
solr6_1               |         at org.alfresco.solr.client.SOLRAPIClient.getTransactions(SOLRAPIClient.java:441)
solr6_1               |         at org.alfresco.solr.tracker.ShardStatePublisher.doTrack(ShardStatePublisher.java:91)
solr6_1               |         at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:242)
solr6_1               |         at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:60)
solr6_1               |         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
solr6_1               |         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
solr6_1               | 2021-04-18 03:25:00.062 ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@69eb86b4_Worker-37) [   ] o.a.s.t.AbstractTracker [alfresco / NODE_STATE_PUBLISHER@1364347872 / IT #1618716300050] Tracking failure. See the stacktrace below for further details.
solr6_1               | org.alfresco.error.AlfrescoRuntimeException: 03180045 GetTransactions return status is 404
solr6_1               |         at org.alfresco.solr.client.SOLRAPIClient.getTransactions(SOLRAPIClient.java:441)
solr6_1               |         at org.alfresco.solr.tracker.ShardStatePublisher.doTrack(ShardStatePublisher.java:91)
solr6_1               |         at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:242)
solr6_1               |         at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:60)
solr6_1               |         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
solr6_1               |         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by aborroy** [comment]
That log indicates that SOLR cannot connect with Alfresco Repository ("GetTransactions return status is 404").

The main reason may be that Alfresco Repository service didn't start successfully.

You may check if every service is up & running using that Docker command `docker ps`. If Alfresco service is not listed, then you need to identify that issue.

Start only the Alfresco Repository service in order to find the real cause.

```
docker-compose up --build --force-recreate alfresco
```

Also, attaching the generated `docker-compose.yml` file to this issue could help to identify the problem.

**Comment by SanjayBandhniya** [comment]
Please find docker-compose.yml.
[docker-compose.zip](https://github.com/Alfresco/alfresco-docker-installer/files/6334865/docker-compose.zip)
Log folder is also not generating.

**Comment by aborroy** [comment]
That works fine, I guess you have not enough resources assigned to your local Docker Engine in Windows.

Assign the right amount of RAM in https://docs.docker.com/docker-for-windows/#resources
