### ISSUE TITLE
Share errors: Could not resolve view with name...

### ISSUE THREAD

**Issue by sergefedorow** [Alfresco/alfresco-docker-installer#77]
Have got a warnings on Share 7.0.0 startup and an errors of Share 6.2.0/7.0.0 during browsing UI pages (6.1 didn't tested).

Docker installer runes on Ubuntu 18.04 LTS Desktop.
Test machine: Google Cloud Platform e2-custom (8 vCPUs, 16 GB memory)
OS: Ubuntu 20.04 LTS server
Docker version: 20.10.6
Docker-compose version: 1.29.2

**7.0 configuration**

> Which ACS version do you want to use? 7.0
> How may GB RAM are available for Alfresco (12 is minimum required)? 16
> Do you want to use HTTPs for Web Proxy? No
> What is the name of your server? my.domain.com
> What HTTP port do you want to use (all the services are using the same port)? 11001
> Do you want to use FTP (port 2121)? No
> Do you want to use MariaDB instead of PostgreSQL? No
> Are you using different languages (this is the most common scenario)? Yes
> Do you want to create an internal SMTP server? No
> Do you want to create an internal LDAP server? No
> Select the addons to be installed: Google Docs 3.1.0, JavaScript Console 0.6, Order of the Bee Support Tools 1.0.0.0
> Are you using a Windows host to run Docker? No
> Do you want to use a start script? No

**Logs**
share_1               | 25-May-2021 12:42:27.815 WARNING [main] org.apache.catalina.webresources.Cache.getResource Unable to add the resource at [/WEB-INF/classes/alfresco/messages/slingshot_ru.properties] to the cache for web application [/share] because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
share_1               | 25-May-2021 12:42:27.819 WARNING [main] org.apache.catalina.webresources.Cache.getResource Unable to add the resource at [/WEB-INF/classes/alfresco/messages/slingshot_ja.properties] to the cache for web application [/share] because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
...
share_1               |  2021-05-25 10:33:26,861  ERROR [alfresco.web.site] [http-nio-8080-exec-6] javax.servlet.ServletException: Could not resolve view with name 'context/shared/url("/share/res/components/documentlibrary/documentlist_v2_f5' in servlet with name 'Spring Surf Dispatcher Servlet'
share_1               |  2021-05-25 11:08:50,670  ERROR [alfresco.web.site] [http-nio-8080-exec-2] javax.servlet.ServletException: Could not resolve view with name 'url("/share/res/components/preview/Pd' in servlet with name 'Spring Surf Dispatcher Servlet'
share_1               |  2021-05-25 12:51:18,682  ERROR [alfresco.web.site] [http-nio-8080-exec-5] javax.servlet.ServletException: Could not resolve view with name 'site/test/url("/share/res/yui/columnbrowser/assets/columnbrows' in servlet with name 'Spring Surf Dispatcher Servlet'
...

**6.2 configuration**

> Which ACS version do you want to use? 6.2
> How may GB RAM are available for Alfresco (12 is minimum required)? 16
> Do you want to use HTTPs for Web Proxy? No
> What is the name of your server? my.domain.com
> What HTTP port do you want to use (all the services are using the same port)? 11001
> Do you want to use FTP (port 2121)? No
> Do you want to use MariaDB instead of PostgreSQL? No
> Are you using different languages (this is the most common scenario)? Yes
> Do you want to create an internal SMTP server? No
> Do you want to create an internal LDAP server? No
> Select the addons to be installed: Google Docs 3.1.0, JavaScript Console 0.6, Order of the Bee Support Tools 1.0.0.0
> Are you using a Windows host to run Docker? No
> Do you want to use a start script? No

**Logs**

...
share_1                  |  2021-05-25 12:36:42,336  ERROR [alfresco.web.site] [http-nio-8080-exec-10] javax.servlet.ServletException: Could not resolve view with name 'context/mine/url("/share/res/modules/cloud/cloud-folder' in servlet with name 'Spring Surf Dispatcher Servlet'
share_1                  |  2021-05-25 12:36:44,368  ERROR [alfresco.web.site] [http-nio-8080-exec-6] javax.servlet.ServletException: Could not resolve view with name 'context/mine/u' in servlet with name 'Spring Surf Dispatcher Servlet'
share_1                  |  2021-05-25 12:37:46,818  ERROR [alfresco.web.site] [http-nio-8080-exec-2] javax.servlet.ServletException: Could not resolve view with name 'site/test/url("/share/res/modules/create-site_a38bada01786d' in servlet with name 'Spring Surf Dispatcher Servlet'
...

**Comment by aborroy** [comment]
I guess this is not related with Alfresco Docker Installer but with Share web app, right?

**Comment by sergefedorow** [comment]
Can't talk about 7.0 but never sow this errors on 6.2 with another docker-compose deployments. So my guesses was this is some combination of configuration.
