### ISSUE TITLE
Documentation of Nginx module: nginx:stable-alpine or angelborroy/acs-proxy ?

### ISSUE THREAD

**Issue by infinite-dao** [Alfresco/alfresco-docker-installer#78]
Hej-hej,

the [README.md (from Mar 12, 2021)](https://github.com/Alfresco/alfresco-docker-installer/blob/e3f2f96125d5b392f36cb5e0f2e8bb01550494ea/README.md) states to have used `nginx:stable-alpine` but actually the generated `docker-compose.yml` for Alfresco 7.0 uses image `angelborroy/acs-proxy` for the Nginx proxy. Right? Perhaps because of `angelborroy/acs-proxy` being a child of `nginx:stable-alpine` so to say, but it seems a bit confusing.

Shouldn't  that be corrected in the README.md or vice versa to be adjusted in the generator template files (if the intend was to use `nginx:stable-alpine` only)?

Thank you.

**Comment by aborroy** [comment]
I guess many people prefers to use default Nginx Docker Image (`nginx:stable-alpine`) with an external configuration file. 

I'll revert configuration in order to use again that way of using the Proxy.

Thanks!

**Comment by aborroy** [comment]
Default NGINX Docker Image is available from version 0.3.0:
https://github.com/Alfresco/alfresco-docker-installer/commit/2e4a1dce1fd849ae48a73690d9fef66de779ec68
