### ISSUE TITLE
Problem after install with ftp enable

### ISSUE THREAD

**Issue by Mouchachnuk** [Alfresco/alfresco-docker-installer#82]
Hello,

I have followed all the instructions. After installing, I can login to Alfresco without any problem, and after a minute, the container listening to port 2121 goes down with this error:
WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/mybatis-3.3.0.jar) to method java.util.HashMap.hash(java.lang.Object)

If I start the container again, everything seems ok.

Any idea?

Kind regards,

Luc

**Comment by aborroy** [comment]
Hello,

Can you attach the produced `docker-compose.yml` file?

Thanks

**Comment by Mouchachnuk** [comment]
[docker-compose.txt](https://github.com/Alfresco/alfresco-docker-installer/files/6862088/docker-compose.txt)
Here is the file (with .txt because of github restrictions)

**Comment by aborroy** [comment]
Sorry, also `.env` file is required.

**Comment by Mouchachnuk** [comment]
# Docker Image versions
ALFRESCO_CE_TAG=7.0.0
SEARCH_CE_TAG=2.0.2
SHARE_TAG=7.0.0
ACA_TAG=2.3.0
POSTGRES_TAG=13.1
API_EXPLORER_TAG=7.0.0
TRANSFORM_ENGINE_TAG=2.3.10
ACTIVEMQ_TAG=5.16.1

# Server properties
SERVER_NAME=localhost

**Comment by aborroy** [comment]
This is working fine at my own. I'm using Mac OS for deployment. What OS are you using?
Do you have enough RAM allocated to Docker Engine?
Some operation that may provoke this issue?

**Comment by Mouchachnuk** [comment]
Hello Angel,

Working on latest version of Mac OSX (11.5). Is there a difference between launching with start.sh script and the docker application?

I have reinstall all files from the beggining and get the same result. Everything works fine for 30 mn and even if I do nothing, I get an EXITED (137) of the container docker-compose_alfresco_1 (port 2121).

:(

**Comment by aborroy** [comment]
I guess there is no difference, I use to run that with docker-compose command.

Can you attach the full log trace from the error?

**Comment by Mouchachnuk** [comment]
Angel,

I have started installation from scratch again... Here is the complete log of installation... You'll see docker-compose_alfresco_1 exited with code 137

I am complitly lost :(

Thx for your help
[install_log.txt](https://github.com/Alfresco/alfresco-docker-installer/files/6867697/install_log.txt)

**Comment by aborroy** [comment]
This looks like a memory problem.

Do you have enough resources (Memory greater than 16 GB) in your Docker Desktop?

https://docs.docker.com/docker-for-mac/

**Comment by Mouchachnuk** [comment]
Damned, it was just a memory issue.

Thx a lot Angel :)
