### ISSUE TITLE
Service 'ocrmypdf' failed to build

### ISSUE THREAD

**Issue by bandhans** [Alfresco/alfresco-docker-installer#86]
I am trying to install alfresco-docker-installer with Alfresco7 in window.
I have selected OCR service during installation.
When I am trying to docker-compose it is giving error.

W: GPG error: http://security.ubuntu.com/ubuntu hirsute-security InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://security.ubuntu.com/ubuntu hirsute-security InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu hirsute InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu hirsute-updates InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu hirsute-backports InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed
E: The repository 'http://archive.ubuntu.com/ubuntu hirsute-backports InRelease' is not signed.
ERROR: Service 'ocrmypdf' failed to build : The command '/bin/sh -c apt-get update && apt-get install -y openssh-server' returned a non-zero code: 100

**Comment by aborroy** [comment]
OCR service is not working with Alfresco 7.

**Comment by iohann95** [comment]
This seems to be fixed now with the new OCR content transformer?

**Comment by aborroy** [comment]
Let me know if the new one works for you.

**Comment by iohann95** [comment]
Ok I will test it today!

**Comment by aborroy** [comment]
Thanks for the feedback!
