### ISSUE TITLE
Apache tika doesn't have enough memory by default

### ISSUE THREAD

**Issue by iohann95** [Alfresco/alfresco-docker-installer#87]
Apache tika doesn't have enough memory by default, and this is easily reproduced. Just try to upload a thousand of big PDF files (~30mb each) using FTP, and apache tika will crash with 137 error. 

Setting mem_limit to 1024m and JAVA_OPTS to -Xms512m -Xmx1024m seems to have solved the problem.

Thank you all!

**Comment by aborroy** [comment]
You mean when using 12 GB as RAM size?

**Comment by iohann95** [comment]
Actually no, no matter how many RAM you choose (eg. 128gb) by default it always sets mem_limit as 512m and JAVA_OPTS as -Xms256m -Xmx512m

**Comment by aborroy** [comment]
Ah, ok, for 6.2 release.

Thanks!

**Comment by iohann95** [comment]
> 
> 
> Ah, ok, for 6.2 release.
> 
> Thanks!

Yes! exactly. f you need any more information about that let me know.

**Comment by marcogianini** [comment]
Good afternoon,

I am also facing a similar scenario. I used the alfresco-docker-installer project and tika has memory error.

We apply more memory to the tika container but it always uses everything I set up. Container processing is always 99%. Can I disable the Tika container?
 tika:
        restart: always
        image: alfresco/alfresco-tika:${TRANSFORM_ENGINE_TAG}
        mem_limit: 4096m
        environment:
            JAVA_OPTS: " -Xms1024m -Xmx4096m"
        ports:
            - 8093:8090

**Comment by aborroy** [comment]
Tika is required, but default memory has been increased to 1024m
