### ISSUE TITLE
SSL certificate expired on https://artifacts.alfresco.co : api-explorer-6.2.0.war failed to download on docker-compose

### ISSUE THREAD

**Issue by CPECkel57155** [Alfresco/alfresco-docker-installer#89]
Hi,

I'm using Alfresco Community Edition 6.2 from alfresco-docker-installer.

When I docker-compose up the api-explorer-6.2.0.war must be download from https://artifacts.alfresco.com but this one has his SSL certificate expired since september 2021 the 4th.

Can you help me ?

Thanks for reading me !

Christophe
![Capture d’écran 2021-09-06 175545](https://user-images.githubusercontent.com/90207226/132241811-6daa55d2-58ad-463b-8316-732bc3121e29.png)

**Comment by iohann95** [comment]
I just tested it and here the certificate is valid until 15/07/2022
Maybe they just updated it?

**Comment by CPECkel57155** [comment]
Yes ! 
They have just renew the certificat !

Thanks I can close this issue !
