### ISSUE TITLE
Access / edit alfresco-global.properties

### ISSUE THREAD

**Issue by apiening** [Alfresco/alfresco-docker-installer#9]
What is the preferred way to access the `/tomcat/shared/classes/alfresco-global.properties` in order to configure user synchronisation with AD etc.?
I could create a volume pointing at the containing folder for the alfresco image in docker-compose.yml but then I would need to copy the current `alfresco-global.properties` manually or would it be recreated based on the configured defaults?
Any hints are greatly appreciated.

**Comment by aborroy** [comment]
You can use a volume for that, like in this template:
https://github.com/keensoft/docker-alfresco

Default alfresco-global.properties should be empty.

Otherwise you can also use environment variables in your docker-compose.yml

**Comment by apiening** [comment]
Hi @aborroy,
thank you very much, this worked perfectly fine!
I'm closing the issue since it is solved.
