### ISSUE TITLE
Installation Alfresco 6.2 Freezes During Run Days

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/alfresco-docker-installer#91]
I installed Alfresco 6.2 using docker-alfresco-installer on an EC2 instance of AWS CentOs with 32 GB Ram and 8 Core.

I connect to a MySql Server RDS Serveless configured with 1000 connection users limit.

The entire environment is in docker as per the project presented. It does not use OCR and the installation was made to be accessed via https.

It has a SAP Connexas Connector amp installed.

And the data is in external volumes, as directed by the project.

Changed some memory settings of containers for better execution.

Monitoring the Database, when it reaches 210 connections it does not allow any more users to log into Alfresco and we have to restart the environment (stop/start), so it disconnects users and allows them to be used. In docker-compose.yml the max connection is set to 300.

I also see that Tika is consuming too much memory and processing.

the composition of my docker-compose.yml:
# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        restart: always
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
            DB: mydb
            API_EXPLORER_TAG: ${API_EXPLORER_TAG}
        mem_limit: 10240m
        environment:
            JAVA_OPTS : '
                -Ddb.driver=org.gjt.mm.mysql.Driver       
                -Ddb.username=xxxxx
                -Ddb.password=xxxxxx%2021
                -Ddb.driver=com.mysql.cj.jdbc.Driver
                -Ddb.host=xxxxxx.cluster-c2xnfdt2ylmm.us-east-1.rds.amazonaws.com
                -Ddb.port=3306
                -Ddb.prefix=mysql
                -Ddb.pool.max=300
                -Ddb.pool.abandoned.detect=true
                -Ddb.url=jdbc:mysql://database-alfresco-prod.cluster-c2xnfdt2ylmm.us-east-1.rds.amazonaws.com:3306/xxxxxxxxxxx?useUnicode=yes\&characterEncoding=UTF-8\&AutoReconnect=true
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.baseUrl=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.host=${SERVER_NAME}
                -Dalfresco.port=443
                -Dalfresco.protocol=https 
                -Dshare.host=${SERVER_NAME}
                -Dshare.port=443
                -Dshare.protocol=https 
                -Daos.baseUrlOverwrite=https://${SERVER_NAME}/alfresco/aos
                -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false 
                -Dftp.enabled=true
                -Dftp.port=2121
                -Dftp.dataPortFrom=2433
                -Dftp.dataPortTo=2434 
                -Dopencmis.server.override=true
                -Dopencmis.server.value=https://${SERVER_NAME}:443
                -Dlocal.transform.service.enabled=true
                -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
                -DlocalTransform.imagemagick.url=http://imagemagick:8090/
                -DlocalTransform.libreoffice.url=http://libreoffice:8090/
                -DlocalTransform.tika.url=http://tika:8090/
                -DlocalTransform.misc.url=http://transform-misc:8090/
                -Dlegacy.transform.service.enabled=true
                -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                -Djodconverter.url=http://libreoffice:8090/
                -Dimg.url=http://imagemagick:8090/
                -Dtika.url=http://tika:8090/
                -Dtransform.misc.url=http://transform-misc:8090/
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Dauthentication.protection.enabled=false
                -XX:+UseG1GC -XX:+UseStringDeduplication

                -Dldap.authentication.allowGuestLogin=false
                -Dldap.authentication.userNameFormat=%s@xxxx.com.xx
                -Dldap.authentication.java.naming.provider.url=ldap://xxxx
                -Dldap.authentication.defaultAdministratorUserNames=admin,it-xxxx

                -Dldap.synchronization.java.naming.security.principal=xxxxx
                -Dldap.synchronization.java.naming.security.credentials=xxxx
                -Dldap.synchronization.groupSearchBase=OU=Alfresco,OU=Grupos,DC=x,DC=com,DC=xx
                -Dldap.synchronization.userSearchBase=DC=xxxxx,DC=com,DC=xx

                -Dauthentication.chain=alfinst:alfrescoNtlm,dc01:ldap-ad

                -Xms2048m -Xmx10240m   
            '
        volumes: 
            - ./../../data/alf_data:/usr/local/tomcat/alf_data
            - ./logs/alfresco:/usr/local/tomcat/logs   
            - ./data/alfresco-global:/usr/local/tomcat/shared/classes
        
        ports:
            - 2121:2121
            - 2433:2433
            - 2434:2434 

    alfresco-pdf-renderer:
        restart: always
        image: alfresco/alfresco-pdf-renderer:${TRANSFORM_ENGINE_TAG}
        mem_limit: 1024m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1024m"
        ports:
            - 8090:8090

    imagemagick:
        restart: always
        image: alfresco/alfresco-imagemagick:${TRANSFORM_ENGINE_TAG}
        mem_limit: 1024m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1024m"
        ports:
            - 8091:8090

    libreoffice:
        restart: always
        image: alfresco/alfresco-libreoffice:${TRANSFORM_ENGINE_TAG}
        mem_limit: 1024m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1024m"
        ports:
            - 8092:8090

    tika:
        restart: always
        image: alfresco/alfresco-tika:${TRANSFORM_ENGINE_TAG}
        mem_limit: 4096m
        environment:
            JAVA_OPTS: " -Xms1024m -Xmx4096m"
        ports:
            - 8093:8090

    transform-misc:
        restart: always
        image: alfresco/alfresco-transform-misc:${TRANSFORM_ENGINE_TAG}
        mem_limit: 1024m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx1024m"
        ports:
            - 8094:8090

    share:
        restart: always
        build:
          context: ./share
          args:
            SHARE_TAG: ${SHARE_TAG}
            SERVER_NAME: ${SERVER_NAME}
        mem_limit: 2048m
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            CSRF_FILTER_REFERER: "https://localhost/.*"
            CSRF_FILTER_ORIGIN: "https://localhost"
            JAVA_OPTS: "
                -Xms512m -Xmx2048m
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "
        volumes: 
            - ./logs/share:/usr/local/tomcat/logs  
    
    solr6:
        restart: always
        build:
          context: ./search
          args:
            SEARCH_TAG: $SEARCH_CE_TAG
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: none
            CROSS_LOCALE: "true"
        mem_limit: 6144m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8080"
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms2048m -Xmx6144m"
            SOLR_OPTS: "
                -XX:NewSize=848m
                -XX:MaxNewSize=848m
            "
        volumes:
            - ./../../data/solr-data:/opt/alfresco-search-services/data 

    activemq:
        restart: always
        image: alfresco/alfresco-activemq:${ACTIVEMQ_TAG}
        mem_limit: 2g
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    content-app:
        restart: always
        image: alfresco/alfresco-content-app:${ACA_TAG}
        mem_limit: 512m
        depends_on:
            - alfresco
            - share

    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        restart: always
        image: angelborroy/acs-proxy:1.2.0
        mem_limit: 512m
        environment:
            - PORT=443
            - PROTOCOL=https 
        depends_on:
            - alfresco
            - solr6
            - share
            - content-app
        volumes:
            - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd 
            - ./config/cert/aws-alfprod.cer:/etc/nginx/localhost.cer
            - ./config/cert/aws-alfprod.key:/etc/nginx/localhost.key 
        ports:
            - 443:443

Why might it be crashing when it gets to 210 connections?

Are there any errors I can't identify? 

Thanks for help

**Comment by aborroy** [comment]
It's hard to guess what's happening there. 

I guess you should design some load testing procedure in order to get more information on the limits of the deployment.

Alternatively, you can increase the connection pool in Alfresco side to 1,000 in order to verify if that is the root cause of the problem.

**Comment by aborroy** [comment]
Not sure if that is related with some Alfresco Transform Tika specific release. 

That service is used for a number of transformations: https://github.com/Alfresco/alfresco-transform-core/blob/master/alfresco-transform-tika/alfresco-transform-tika/src/main/resources/tika_engine_config.json

My guessing is that you are working with heavy PDF Files, so Tika needs to extract text for Indexing the content of the file. 

If that if the case, you could try to decrease the limit for "maxSourceSizeInBytes" for PdfBox transformer: https://github.com/Alfresco/alfresco-transform-core/blob/master/alfresco-transform-tika/alfresco-transform-tika/src/main/resources/tika_engine_config.json#L63

You will lose the ability to search in content of large PDF Files, but likely the whole system will be working as expected consistently.

Another approach would be to install Tika Container in a different server, so those peaks in resources consumption don't affect to the overall performance of the Alfresco Repository. 

In any way, I guess you need to identify the root cause of this problem, that may be related with some specific input files and the text extraction process.

**Comment by marcogianini** [comment]
Angel,

we do have quite large PDF files (over 20Gb for example).

We are seeing the removal of search for content in Solr (solrcore.properties) leaving only metadata (default and customizable).

This change can be efficient or will we also have to change the "maxSourceSizeInBytes" for PdfBox transformer?

Thanks

**Comment by aborroy** [comment]
If you exclude content to be searchable from Solr, Tika problem will be solved. But users won't be able to search for contents.

If you decrease the "maxSourceSizeInBytes", Tika problem will be mitigated. And users will be able to search for contents (under the specified size limit).

You can choose one of this, but I guess it doesn't make sense to apply both.

**Comment by marcogianini** [comment]
Thanks for the prompt feedback.

I'm going to test change the solrcore.properties. As I have done on another server and follow the result of Tika.

I think this is the way, because we don't want (in this case) to search for the contents of the file. Only by metadata.

When you have the result put here the applied solution.
