### ISSUE TITLE
Project to install Alfresco Enterprise

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/alfresco-docker-installer#93]
Hello.

Can I use this project to install Alfresco Enterprise? Do you have a special project for this?

If it's the same, how can I proceed?

Thanks

**Comment by aborroy** [comment]
We are using this one internally:
https://github.com/Alfresco/SearchServices/tree/master/e2e-test/generator-alfresco-docker-compose

Not sure if that helps.

**Comment by marcogianini** [comment]
Thanks.

I'll test this.

Marco
