### ISSUE TITLE
Unable to validate database schema using MariaDB

### ISSUE THREAD

**Issue by iohann95** [Alfresco/alfresco-docker-installer#95]
Using MariaDB, when Alfresco is creating the databases, in the end it gives me an exception "Unable to validate database schema." the it cascades some "Unable to execute export." errors.

It still works though... But it seems to be fixed if we update mysql-connector to the latest 8.0.26 version.
(as a bonus it also fixes compatibility with latest build of original mysql)

Thanks!!

**Comment by aborroy** [comment]
I've switched to native MariaDB JDBC client. 
Let me know if that works for you.
